- Cargo.lock
- Cargo.toml
- src/ast.rs
- src/main.rs
- src/modules.rs
This is the frontend-agnostic AST that we will use to perform typechecking and code emitting.
Loosely modelled after the Haskell version.
> Create the AST type definitions.

- hash-ast/src/parse.rs
Fixed issue with resolve_path prematurely checking if a path to a module exists
> fix: resolve_path not finding module without 'hash' extension

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/parse.rs
- compiler/hash-ast/src/visualise.rs
- compiler/hash-pest-parser/src/grammar.pest
- compiler/hash-pest-parser/src/translate.rs
- compiler/hash/src/interactive/command.rs
- compiler/hash/src/interactive/mod.rs
- compiler/hash/src/main.rs
- examples/lang_manifest.hash
- examples/visual.hash
This PR essentially brings an AST visualiser that can display AST nodes into a tree format. This visualiser can be invoked via the interactive console by specifying the command `:d` and then visualising the following expression.
> Visualising AST

- docs/src/advanced/if-statement-transpilation.md
- docs/src/advanced/intro.md
- docs/src/advanced/loop-transpilation.md
- docs/src/advanced/type-inference.md
- docs/src/basics/conditionals.md
- docs/src/basics/enum-types.md
- docs/src/basics/loops.md
- docs/src/basics/modules.md
- docs/src/basics/operators.md
- docs/src/basics/pattern-matching.md
- docs/src/basics/primitive-types.md
- docs/src/basics/types-assertions.md
- docs/src/basics/variables.md
- docs/src/interpreter/backends.md
- docs/src/interpreter/intro.md
- docs/src/interpreter/options.md
- docs/src/introduction.md
- docs/src/standard-library/intro.md
This PR fixes all spelling mistakes and updates the style of error reporting as per the work done in `hash-reporting`.
> Docs: update documentation on error report style and fix spelling mistakes.

- compiler/hash-ast/src/module.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-utils/src/lib.rs
- compiler/hash-utils/src/tree_writing.rs
This can be used to print any sort of tree-like structure in various styles.
> Add a generic tree writer in `hash_utils`.

- Cargo.lock
- compiler/hash-alloc/src/collections/row.rs
- compiler/hash-ast/src/error.rs
- compiler/hash-ast/src/fs.rs
- compiler/hash-ast/src/location.rs
- compiler/hash-ast/src/parse.rs
- compiler/hash-ast/src/resolve.rs
- compiler/hash-parser/Cargo.toml
- compiler/hash-parser/src/backend.rs
- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/lexer.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-reporting/src/errors.rs
- compiler/hash-reporting/src/report.rs
Using ADTs to represent errors in the parser is a better solution in the long run and avoids a significant amount of redundant string allocations.
This fixes #71.
> Use ADTs for errors in the parser.

- compiler/hash-interactive/src/lib.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-pest-parser/src/translate.rs
This fixes #56.
Infix function calls that follow the shape of a.b() where the function b is applied onto the argument a wasn't being properly parsed in the pest parsing backend.
This patch fixes the issue and unifies the behaviour of the pest and self hosted parser.
> fix #36: infix function calls weren't being processed correctly.

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/lib.rs
- compiler/hash-ast/src/location.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-ast/src/visualise.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-pest-parser/src/translate.rs
This pull request adds an implementation of the visitor pattern for the AST node structure. This is done to avoid repetition when recursing into children, for example in typechecking and visualisation.
The `AstVisitor` trait contains methods which can be implemented for each node in the tree. This is to be used in conjunction with functions inside `visitor::walk::*`, which traverse into the children and return the visitor results.
Each node has its own "return type" within the visitor, which allows for arbitrarily complicated traversal of the tree. Furthermore, enum types within the AST have `*_same_children` helper functions within `visitor::walk`, which automatically matches on the variants and traverses the variant enum members, as long as all variants have the same return type in the …
> Implementation of AST Visitor

- compiler/hash-parser/src/gen.rs
- tests/parser/tests/cases/should_pass/pattern_matching_let/case.hash
> Parser: use '=' instead of ':' for namespace destructuring

- compiler/hash-ast/src/module.rs
- compiler/hash-ast/src/parse.rs
- compiler/hash-parser/src/backend.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-reporting/src/reporting.rs
This is done for the sake of consistency with `parse_interactive`, and provides more information about a module (i.e. the span of the file that contains it, as well as the filename of the file).
This is also needed to be able to pass a module into an `ast::visitor::AstVisitor`.
> Wrap `ast::Module` nodes inside `ast::AstNode` in `Modules`

- Cargo.lock
- compiler/hash-ast/Cargo.toml
- compiler/hash-ast/src/ident.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visualise.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-utils/src/lib.rs
This PR improves the handling of identifiers in the parser and removes a bunch of redundant behaviour in the `IdentifierMap` type. The changes can be summarised by the following points:
- Use `ThreadLocal` to keep a wall on each thread in order for faster allocations when creating identifiers and inserting them into the identifier map.
- Don't even try to allocate before looking up if an identifier exists in the map.
- Better naming convention in the `IdentifierMap` type:
- `get_ident` gets an identifier 
- `create_ident` creates an identifier :))
- Introduced a concept of `CORE_IDENTIFIERS` which is a wrapper around `IDENTIFIER_MAP` that contains inserted core identifiers like the primitives and the `_` identifier.
- Removed dependency on `parking_lot` as we no longer need to lock the …
> Parser: Improve and refactor `Identifier` handling

- compiler/hash-typecheck/src/traits.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/types.rs
- compiler/hash-typecheck/src/unify.rs
- compiler/hash-typecheck/src/writer.rs
This PR implements an MVP version of trait resolution and inference, including inferring trait implementations from function call arguments and surrounding context.
In order to achieve this feat, the nature of unknown types has changed. Each unknown type carries an ID (`UnknownTypeId`, which points to a slot with an optional "resolved" type). It is no longer the case that `TypeId`s themselves can have their type swapped; this is only true for unknown types now. This allows types to be entirely deep-copied without losing the identity of each unknown type within them. This theoretically improves type inference across the board, not just for traits.
There are a few more things to tackle after this PR regarding traits and generic resolution:
- Implement support for trait bounds.
- Find a way …
> Typechecking: Minimum traits

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-interactive/src/lib.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-reporting/src/reporting.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/unify.rs
- compiler/hash-utils/src/tree_writing.rs
This patch implements tuple types in the typechecker by modifying the way they are represented in the AST. 
Additionally:
- This also adds some minor improvements to AST visualisation. 
- Reporting boundary between line numbers and code is highlighted in blue to give a clear boundary between both elements.
> Typechecker: Implement tuple types

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/types.rs
- compiler/hash-typecheck/src/unify.rs
- compiler/hash-typecheck/src/writer.rs
Similarly to tuple types, the current way of handling function types
was to check if an identifier was being used to denote the function
as 'Function' which was very hacky. This patch removes this behaviour
and adds a new variant to the `Type` variant called `Fn`.
This makes it considerably easier to work within the typechecker
and the visualiser.
closes #119
> AST: use special variant for function types.

- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_fail/missing_comma_in_struct_field/case.hash
When struct literals were missing a comma somewhere in the middle of
the brace block, the parser would abort parsing any fields after it
because it considered that there cannot be anything after the
comma. However, this wasn't the correct behaviour as there might
be just a missing comma afterwards, and it will just fail to
parse everything else in the block. This patch fixes this
behaviour and reports the error.
This also improves the way token kinds are being reported in the
parser reporter logic to make more sense (in terms of English).
Also, when struct symbols (literals and patterns) weren't in scope, the incorrect span was being used to report the missing symbol. Instead of using the entire struct literal span, it should only be using the span of the name.
> Struct literal fix

- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/state.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/types.rs
- compiler/hash-typecheck/src/unify.rs
This PR adds support for namespace patterns, which can be used to extract contents from modules.
> Typecheck namespace patterns

- Cargo.lock
- compiler/hash-reporting/Cargo.toml
- compiler/hash-reporting/src/reporting.rs
- compiler/hash-utils/src/lib.rs
- compiler/hash-utils/src/path.rs
On Windows, paths are defaulted to using the `UNC` format which enables paths to be considerably longer than the default value of 260. However, we don't want to show the paths as this, we want to display them with the drive beginning.
Before on Windows, it prints:
```
error[0006]: Symbol `T` is not defined in the current scope.
--> \\?\C:\Users\Alex\Desktop\hash-org\lang\examples\ignored\variety.hash:299:31
298 |
299 |   let next<Enumerate<$I>, (i32, T)> where next<$I, $T> = (iterator) => {
|                                 ^ not found in this scope
300 |       match next(iterator.item) {
```
Now it prints:
```
error[0006]: Symbol `T` is not defined in the current scope.
--> C:\Users\Alex\Desktop\hash-org\lang\examples\ignored\variety.hash:299:31
298 |
299 |   let next<Enumerate<$I>, …
```
> fix: Don't display UNC paths on windows

- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/lexer.rs
- compiler/hash-source/src/location.rs
- tests/parser/tests/cases/should_pass/tuple_literals/case.hash
- tests/parser/tests/cases/should_pass/tuple_types/case.hash
- This patch adds support within the parser to treat `()` as an empty tuple whilst allowing for the old `(,)` syntax to also persist. (Fixes #147)
- This also fixes a parser bug involving invalid float literal exponents which causes the compiler to crash when reporting the issue (fixes #153).
> parser: Empty tuple syntax `()`

- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- tests/parser/tests/cases/should_pass/function_defns/case.hash
- tests/parser/tests/cases/should_pass/function_literals/case.hash
- tests/parser/tests/cases/should_pass/simple_import/file.hash
- tests/parser/tests/cases/should_pass/traits_defns/case.hash
This patch addresses the issue specified in #151. Annotated
function return types are now denoted using a `->` for both
in function literals and within function types.
Before there was a different syntax for specifying the return
type of a function within a type (using the `=>` fat-arrow) and
within function literals (`:` colon). This was inconsistent and
sometimes hard to read. This change in syntax should clear up
the ambiguity of annotating return types within functions.
> parser: Change syntax of fn return types

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/lexer.rs
- compiler/hash-source/src/location.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_fail/expresionless_directive/case.hash
- tests/parser/tests/cases/should_pass/basic_directives/case.hash
- tests/parser/tests/cases/should_pass/block_directive/case.hash
- tests/parser/tests/cases/should_pass/compound_pattern_matching/case.hash
- tests/parser/tests/cases/should_pass/compount_pattern_matching_with_structs/case.hash
- tests/parser/tests/cases/should_pass/multiple_directives/case.hash
- tests/parser/tests/cases/should_pass/nested_match/case.hash
- tests/parser/tests/cases/should_pass/parenthesised_match_statement/case.hash
- tests/parser/tests/cases/should_pass/struct_pattern_matching/case.hash
- tests/parser/tests/cases/should_pass/tuple_literals/case.hash
- tests/parser/tests/cases/should_pass/tuple_types/case.hash
This patch implements a basic form of directives within the parser and parser tooling.
https://github.com/hash-org/lang/pull/154 should be merged before this.
> lang: Implementation for directives

- .github/ISSUE_TEMPLATE/bug_report.md
- compiler/hash-parser/src/error.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash/src/crash_handler.rs
- docs/src/SUMMARY.md
- docs/src/basics/directives.md
- docs/src/basics/functions.md
- docs/src/basics/generics-polymorphism.md
- docs/src/basics/operators.md
- docs/src/basics/primitive-types.md
- docs/src/basics/types-assertions.md
- tests/parser/tests/cases/should_pass/function_defns/case.hash
- tests/parser/tests/cases/should_pass/function_literals/case.hash
- tests/parser/tests/cases/should_pass/simple_import/file.hash
- tests/parser/tests/cases/should_pass/traits_defns/case.hash
This patch updates the documentation book and updates the CI to include a new bug report template
- Add basic documentation on directives
- Update some snippets in the documentation to reflect syntax changes.
- adds an issue template for creating a bug report.
- updates the compiler panic URL to default to using the "bug report" template.
> docs: Update documentation and use GitHub issue template

- compiler/hash-parser/src/gen.rs
- compiler/hash-typecheck/src/traverse.rs
This patch fixes an issue with operator locations such as '<'
not being properly recorded due to the function `transform_compound_ord_fn`
not taking the operator location into consideration. This patch makes
the function take in the operator kind and location.
Additionally, in `hash-typecheck`, the reporting for the symbol
resolution was referencing the whole `VariableExpr` location
instead of just the location of the subject of the expression.
fixes #159
> report: fix issue with operator locations being under reported.

- compiler/hash-typecheck/src/traverse.rs
The fact that "true" and "false" are variables and not enum variants
means that they cannot be used within a pattern, and instead they are
assumed to be pattern bindings, which overwrites them with whatever the
subject of the match case is. This results in unexpected behaviour such
as:
```rs
match 1 {
true => {
// Now `true` is of type `i32`
}
}
```
The actual solution would be to make booleans enums, which should
automatically fix this problem. However, this is a quick fix to get
match statements (and following from that, if and while) to work.
> Typechecking: Fix boolean patterns

- compiler/hash-parser/src/gen.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/sources.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/types.rs
- compiler/hash/src/main.rs
This patch expands the `hash-pipeline` to have modes that are
derived from the provided command-line arguments. By doing this,
the compiler now supports `ast-gen` mode again which will only
run the pipeline up to the typechecking stage.
With `ast-gen` mode, this also means that when the compiler runs
with the `--debug` flag, it will print the generated AST for
each module source that has been parsed.
> Compiler modes: Re-integrate modes with `hash-pipeline`

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/scope.rs
- compiler/hash-typecheck/src/traverse.rs
This patch adds source location data to components of an `AccessName`. This means that when symbols are being resolved in the typechecking stage, more accurate errors can be provided when certain variables are not in the file scope, or in the scope of a namespace.
fixes #160
> Reporting: More accurate error locations for unresolved symbols

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/keyword.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/lexer.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-typecheck/src/traverse.rs
This patch makes boolean literals more distinct at the parsing level to avoid confusion at later stages.
Should be checked out after #170
> Parser: Boolean literals

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/keyword.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-parser/src/lexer.rs
- compiler/hash-parser/src/token.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_pass/unsafe_blocks/case.hash
This patch adds support for specifying that some expressions are unsafe. This is required for the planned changes that are to occur in the core of the language.
> Unsafe expressions

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_fail/missing_default_value_in_function_literal/case.hash
- tests/parser/tests/cases/should_fail/missing_type_in_function_literal/case.hash
- tests/parser/tests/cases/should_pass/function_literal_with_default_value/case.hash
This patch adds support to the parser and typechecker (partially) for supporting default function arguments.
What still needs to be done?:
> Parser: support for defining default values for function arguments.

- docs/src/features/functions.md
- docs/src/features/primitives.md
- docs/src/features/type-functions.md
- docs/src/features/types.md
This is the first in a couple of PRs that add documentation about general type-related things in Hash.
> Docs: Add initial grammar for types

- docs/src/features/types.md
It is not clear how to infer the type of a type, because it can be any
level of refinement.
For example, if `T` implements `Copy` and `Eq`, the following are true:
```
T: T
T: Copy
T: Eq
T: Copy ~ Eq
T: Type
```
Given this, which bound should be inferred? The answer is that we
shouldn't try to infer a bound, and it should be `Type` by default
unless someone specifies otherwise (with an explicit `: MyBound`).
> Docs: Remove unnecessary ":=" variant in type function arguments

- compiler/hash-alloc/src/collections/row.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/block.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/literal.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-parser/src/parser/operator.rs
- compiler/hash-parser/src/parser/pattern.rs
- compiler/hash-parser/src/parser/types.rs
- compiler/hash-source/src/location.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_pass/existential_type/case.hash
This patch implements the slightly amended type parsing and adds support for the new specified type [grammar](https://hash-org.github.io/lang/features/types.html).
In summary, this patch changes/adds the following:
- Remove `TypeVar`, `Infer` and `Existential` variants from`Type`
- `Set`, `Map` and `List` are now variants of `Type`
- `NamedType` no longer holds `type_args` as that is structured as a `TypeFunctionCall`
- Added `MergedType` which allows you to specify the intersection of types  (primarily used in type bounds).
- Added support for parenthesising a `Type` which makes it a `GroupedType`. The difference between a `TupleType` and `GroupedType` is that `TupleType`s must have multiple members or single element `TupleType`s should have a trailing comma at the end of the …
> Parser: Refine type parsing

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/pattern.rs
- compiler/hash-token/src/keyword.rs
- compiler/hash-token/src/lib.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_pass/visibility/case.hash
This patch adds declaration visibility modifier support within the `Lexer`, `Parser`, and `AST` crates.
> Parser: Added declaration visibility

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-token/src/keyword.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_pass/traits_defns/case.hash
- tests/parser/tests/cases/should_pass/type_exprs/case.hash
This patch adds a new variant to expressions which allows for explicitly writing types by specifying the `type` keyword at the 
beginning of the expression.
In regards to renaming the `TypedExpr` to `AsExpr`, this is the reasoning:
A new type of expression is planned to be added which provides a
method of putting a type within an expression by prefixing the
expression with the `type` keyword.
This naming shift from `TypedExpr` to `AsExpr` is to avoid the confusion
between `TypeExpr` and `TypedExpr`.
> Language: add support for `type` expressions

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-token/src/keyword.rs
- compiler/hash-token/src/lib.rs
- compiler/hash-typecheck/src/traverse.rs
- tests/parser/tests/cases/should_pass/impl_blocks/case.hash
This patch adds support for the following:
- `impl` blocks which are now part of the `Block` enum and are attachable to declarations via the `~=` operator.
> Language: support trait implementation definition constructs

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-source/src/string.rs
- compiler/hash-token/src/lib.rs
> refactor: use `From` utility traits for `StringLiteral` and `Identifier` instead of directly accessing maps

- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/reader.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/storage/sources.rs
This provides accessors methods to most things stored in the `storage`
module. Closes #258, #259.
> Add `PrimitiveReader` to simplify accessing terms and other data

- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This is a major step towards unification. Substitution has been entirely implemented, including various technicalities for type functions and definitions (see code docs). Furthermore, a `AppSub` term has been added which is added when a definition tries to be substituted. This is to be resolved when namespace access is resolved, so that the substitution can be forwarded onto the type and values of the members.
Closes #261.
> TC: Implement term substitutions in `Substitutor`

- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/primitives.rs
A critical aspect of type inference is to be able to merge/unify substitutions in order to accumulate inferred types and resolve unknown type variables across the program. This PR implements unification of substitutions, as detailed in the paper <https://www.researchgate.net/publication/221600544_On_the_Unification_of_Substitutions_in_Type_Interfaces>. This is another step towards the completion of term unification in the typechecker. Closes #263.
> TC: Implement substitution unification

- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This is another important step towards type inference. By doing this, one can now instantiate type function return values based on their type arguments, which can be used to implement type function application. This is needed for implementing #271 as well as #232.
Closes #270.
> TC: Implement discovering free variables in a term

- compiler/hash-ast-passes/src/analysis/block.rs
- compiler/hash-ast-passes/src/analysis/error.rs
- compiler/hash-ast-passes/src/analysis/mod.rs
- compiler/hash-ast-passes/src/lib.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/block.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-typecheck/src/storage/state.rs
> semantics: check that `return` statements are only used within functions

- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This PR implements resolving the type of any given term, to produce another term. This is very useful for type inference and needed for unification. This operation lives in `Typer`. Also, this PR implements struct field accessing for runtime terms (which was missed in the last simplification PR #282), and also adds scaffolding for term validation in `Validator`. 
Closes #285.
The next step after this PR is to tackle #284, namely term validation, which should be relatively quick. After that, unification can be tackled directly.
> TC: Implement getting the type of a term

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-passes/src/analysis/block.rs
- compiler/hash-ast-passes/src/analysis/mod.rs
- compiler/hash-ast-passes/src/analysis/pat.rs
- compiler/hash-ast-passes/src/diagnostics/error.rs
- compiler/hash-ast-passes/src/diagnostics/mod.rs
- compiler/hash-ast-passes/src/diagnostics/warning.rs
- compiler/hash-ast-passes/src/lib.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/expression.rs
It was decided that argument ordering validation should occur at the tc stage rather than the semantic stage since more information can be provided about the error.
> semantics+ast: some minor refactoring and clean-up

- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/traits.rs
- compiler/hash-reporting/src/reporting.rs
- compiler/hash-vm/src/vm.rs
- tests/parser/tests/test_runner.rs
This patch re-works the pipeline in order to cope with the fact
that some diagnostics might be warnings, and it is ok to
continue compiling. This also generalises how the pipeline
deals with diagnostics from all the generated stages.
The pipeline now collects errors within `compiler_state` and
only prints them when the pipeline terminates. It also reports
how many warnings and errors were generated when running a particular
job.
closes #289
> pipeline: continue running stages when diagnostics are only warnings

- compiler/hash-source/src/identifier.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/ops/params.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-utils/src/lib.rs
This PR implements unification of terms, completing the core of the typechecker (along with simplification, substitutions, and typing). Unification takes two terms A and B, and ensures that A is a sub-term or equal term to B, that is, any instance of A can be used where B is required. This asymmetry only applies to instantiable terms (level 1 and above); for uninstantiable terms, unification is simply equality checking. Unification produces a substitution as a result, which can be applied to surrounding terms to infer more information about them (this is how type inference works).
The remaining tasks in the typechecker are:
- Implement further term validation (see `validate.rs`) (see #284)
- Write tests for simplification, unification, substitutions, and typing (see #296).
- Implement …
> TC: Implement term unification

- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This PR includes a set of minor improvements to term simplification, notably flattening nested `Term::Merge`s. Furthermore, the `Root` term is introduced, which is used as the type of `TraitKind` and `TyFnTy`. This is needed because typing `TyFnTy` as `TraitKind` is not consistent (since it is not a trait). The `Root` term is also typed as `Root`, and is the only term to do so. This PR is a precursor to tackling #284.
> TC: Minor improvements to simplification and adding Root term

- compiler/hash-ast-passes/src/diagnostics/error.rs
- compiler/hash-ast-passes/src/diagnostics/mod.rs
- compiler/hash-ast-passes/src/diagnostics/warning.rs
- compiler/hash-ast-passes/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/parser/error.rs
- compiler/hash-pipeline/src/fs.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/traits.rs
- compiler/hash-reporting/src/builder.rs
- compiler/hash-reporting/src/lib.rs
- compiler/hash-reporting/src/report.rs
- compiler/hash-reporting/src/reporting.rs
- compiler/hash-reporting/src/writer.rs
- compiler/hash-vm/src/error.rs
- compiler/hash-vm/src/vm.rs
- compiler/hash/src/main.rs
- tests/parser/tests/test_runner.rs
This PR is a minor refactor of the `hash_reporting` crate, primarily designed to split the logic of the reporting into separate and more manageable modules. This PR also fixes a bug where line numbers of the erroneous span would sometimes be highlighted incorrectly. 
Further improvements to the `hash_reporting` crate such as splitting the definition of the various reporting components and the logic to render the reporting components will also be added (but in a separate PR).
closes #299
> reporting: split logic into modules and fix span highlighting bug

- compiler/hash-reporting/src/builder.rs
- compiler/hash-reporting/src/lib.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-reporting/src/report.rs
- compiler/hash-reporting/src/writer.rs
This patch adds a separation of logic for rendering reports and the actual definitions of the data structures. This patch also introduces modes for printing reports, specifically `block` and `line` modes. The `line` mode is self-explanatory and is used to render reports with single line spans, whereas the `block` mode is used for larger spans.
closes #290 
There is still some work to be done when shortening even larger spans by omitting line spans and replacing the lines with `..` as detailed in #290
> reporting: implement `block` mode for larger spans

- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This PR implements the validation of traits and modules. This consists of validating each member of a trait/mod/impl, and ensuring that an `impl X` definition implements `X` correctly. After this PR, #312 needs to be tackled, as well as traversal (concurrently).
Closes #304.
> TC: Implement validation of traits and modules

- .github/workflows/rust.yml
- Cargo.lock
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash/Cargo.toml
- The pre-commit hook (powered by [`cargo-husky`](https://github.com/rhysd/cargo-husky)) should lead to fewer "Fix {formatting,clippy,tests}" commits.
- The build step was removed from CI because CI takes a very long time and building doesn't check for anything more than what `cargo clippy` does.
Closes #316.
> Add pre-commit hook for format/lint/test, and remove build step from CI.

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/reporting.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This patch fixes the two outstanding todos within `ast.rs`:
- `VariableExpr` should not have `type_args` on it and any expression which is an `AccessName` followed by type arguments should be parsed as a `TypeFunctionCall`.
- rename `FunctionDefArg` and friends to `FunctionDefParam`
This patch also adds basic information about term locations during traversal, which has led to the first error report within typechecking to be rendered with locations!
> AST+TC: fix todos within the AST and add basic location information during tc traversal

- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/storage/scope.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR also adds formatting for scopes, which should help in debugging!
Declaration traversal is not yet fully complete, because it does not deal with mutability or visibility (some checks need to be implemented for this). Furthermore, the only patterns supported right now are binding patterns.
Closes #324.
> TC: Implement declarations and add validation to existing traversals

- compiler/hash-ast-passes/src/diagnostics/error.rs
- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/pattern.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/mod.rs
- compiler/hash-typecheck/src/diagnostics/params.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/diagnostics/symbol.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/params.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/reporting.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
This PR adds implementations for reporting all of the remaining error variants.
closes #300
> TC: implement reporting for remaining members of `TcError`

- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR implements traversal of function types and reference types. It also adds a `kind` field to the `RefKind` struct in the AST visitor, which was missing. Furthermore, it treats the `_` type as an infer-type, which means it gets assigned an unresolved term.
This PR also fixes a bug with substitutions. It seems the paper that is referenced for substitution unification has a typo, in that it writes T0 instead of T1 in a specific step. At least this is the assumption :D. Substitutions seem to work correctly now. Also, substitution merging is fixed to use a combination of merging and unification.
Closes #343, closes #342. Does not address #327 yet, contrary to the branch name, because this change is deemed too big to be done in one PR.
> TC: Implement traversal of function types, reference types, infer type

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/types.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR implements AST traversal and typechecking of type functions and type function types. It also fixes the previous implementation of validation/simplification for type functions, to enter parameter scope before validating the return type and value.
Closes #341.
> TC: Implement traversal of type functions

- compiler/hash-parser/src/parser/types.rs
- tests/parser/tests/cases/should_pass/type_function_types/case.hash
> parser: fix over eager token skipping in `parse_type_function`

- compiler/hash-ast/src/ast.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-vm/src/stack.rs
This PR implements traversal of merge types and type function calls, completing the bulk of the basic type traversal (minus definitions like structs, enums).
Closes #327.
> TC: Traverse merge types and type function calls

- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/macros.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This PR adds `FnCall` as a new level 0 term, which should make traversal of function calls trivial. Works towards #328. Supports, constructors, enum variants, and functions.
> TC: Implement simplification of function calls

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR closes #328. It also renames `RuntimeInstantiable` to just `Type` and makes it the default for type parameters. Furthermore, this PR implements `Clone` for all AST nodes, where before this wasn't the case for some reason..
> TC: Traverse function calls and constructors

- compiler/hash-typecheck/src/traverse/mod.rs
This patch implements the following traversal methods:
- `loop` blocks, 
- `continue`, `break`, and `return` expressions
-  `deref`, `ref` expressions
- scaffold implementation for `unsafe` and `directive` expressions
- `map`, `set`, `list` type traversals
closes #327
closes #333
> Tc: implement traversal for more expressions and types

- Cargo.lock
- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-typecheck/Cargo.toml
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This is needed to tackle #363 as well as for the "never" type which was missing up until now. In many ways, unions are dual to merges (and to tuples in other contexts). Currently only nominals can be "unioned", to support enum definitions as unions of structs. In the future this might change.
Closes #357.
> TC: Introduce unions and the "never" type

- compiler/hash-typecheck/src/ops/reader.rs
- compiler/hash-typecheck/src/storage/sources.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This includes marking sources as already checked. However, this does not handle cyclic imports yet, and currently the module resolution will loop forever. This should be tackled in a separate PR once we figure out how to deal with recursive definitions (see #367). 
Closes #335.
> TC: Implement traversal for imports

- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This is the final sub-task of implementing trait def/impl/mod blocks.
closes #340
> tc: implement traversal for `trait impl`s and `impl` blocks

- compiler/hash-ast/src/ast.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/traverse/mod.rs
In addition, this PR introduces convenience methods to make dealing with locations in the TC visitor more ergonomic.
Closes #332, closes #373.
Also opened #372 in order to actually make method calls work--right now you have to surround the subject in parentheses `(a.b)(c)` vs `a.b(c)`.
> TC: Implement traversal of index expressions and property access

- compiler/hash-ast-desugaring/src/visitor.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/operator.rs
- compiler/hash-parser/src/parser/types.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- docs/src/features/types.md
This patch adds support within the AST and parser for
union type notation. The patch introduces the notion
of type operators which are equivalent to binary operators
but for types. Currently, `TyOp` has two variants which
are `Union` and `Merge`, where union operator has a
higher precedence then the merge operator.
closes [#362](https://github.com/hash-org/lang/issues/362)
> parser+ast: support for `union` type notation

- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- tests/parser/tests/test_runner.rs
This is needed for a few reasons:
1. So that we can support a typeof expression in the future
2. To eliminate the current inconsistency that typeof(Root) = Root.
3. To be able to implement mutually recursive definitions, by deferring the typing of various terms (instead leaving them as typeof(X)) until they are resolved.
Closes #385.
> TC: Add `Term::TyOf` in order to be able to perform algebra with types of terms

- compiler/hash-ast-passes/src/analysis/block.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-typecheck/src/traverse/scopes.rs
This is in order to be able to implement recursive definition support
from a central place.
Another change is to allow ending expressions in constant scopes,
treating them as the final declaration (similar to how tuples etc do not
need an ending delimiter).
> TC: Factor out constant scope traversal

- Cargo.lock
- compiler/hash-typecheck/Cargo.toml
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/location.rs
- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/storage/patterns.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR implements patterns in a similar way that terms are implemented (with stores etc). This is to aid the process of implementing pattern-related operations like usefulness checks, as well as to be able to represent patterns while traversing.
The next step after this PR is to add functionality to get the type of a pattern (probably from within `Typer`), and then to implement traversal of patterns (part of #329, #331), and then finally usefulness (i.e. given a `Term` and a set of `Pattern`s, are all the patterns useful to match the given term).
To do this, the concept of "literal terms" is added, which is a natural extension of runtime terms to include basic literals like integers, characters and strings. These are now used when traversing literals, and this opens the door to literal …
> TC: Implement patterns as typechecking primitives, and literal terms

- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/params.rs
- compiler/hash-typecheck/src/ops/patterns.rs
- compiler/hash-typecheck/src/ops/reader.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/location.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-typecheck/src/traverse/sequence.rs
This PR implements pattern and control flow traversal. There are still a few things to be done:
- Adding constructor pattern bindings to scope: #407 
- Matching or patterns: #409 
- Matching mod patterns: #408 
Closes #410, #331, #329.
> TC: Implement pattern matching, as well as pattern and control flow traversal

- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/diagnostics/symbol.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/ops/pats.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR implements assign expression traversal. It also adds `ScopeVar` and `BoundVar` in preparation for #367 and #419 (work to be continued in separate PRs). NameFieldOrigin is also removed since it was considered to be too flaky and prone to panics. See #423 instead.
Closes #125.
> TC: Implement assignment and start dealing with recursive definitions

- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/storage/store.rs
These are meant to replace all the currently hardcoded implementations of stores, without interior mutability. Hopefully with this change, three things can happen:
1. The typechecker ops structs can take `&self` rather than `&mut self`, which should save a lot of unnecessary clones. The unavoidable clones (if needed) are done in the new store implementations.
2. Term lists such as `Merge` and `Union` do not need to hold `Vec`s anymore, and instead can point to `SequenceStore`s. `SequenceStore` elements are stored inline, which should be a performance boost.
3. The plan is to use `SequenceStore` as a base to implement `ParamList` and `Scope` in a more performant way and with interior mutability.
Works towards #445.
> TC: Implement generic stores with interior mutability

- compiler/hash-typecheck/src/exhaustiveness/construct.rs
- compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/matrix.rs
- compiler/hash-typecheck/src/exhaustiveness/range.rs
- compiler/hash-typecheck/src/exhaustiveness/stack.rs
- compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/fmt.rs
This PR fixes two issues that were present within the exhaustiveness sub-system and also implements converting ranges into `Range::Pat` from within the sub-system when producing error reports.
> TC: fix exhaustiveness issues

- Cargo.lock
- compiler/hash-ast/src/ast.rs
- compiler/hash-typecheck/src/exhaustiveness/constant.rs
- compiler/hash-typecheck/src/exhaustiveness/construct.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/matrix.rs
- compiler/hash-typecheck/src/exhaustiveness/range.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/ops/exhaustiveness.rs
This patch fixes several issues with the exhaustiveness checking:
- `Pat::Const` should be handled as a wildcard with the given type of subject, unless the pattern itself is an enum variant which is currently not implemented. fixes #461 
- `Pat::Access` does not need to perform any special handling since the type of the pattern should already be resolved, it just needs to pass in `ty` to deconstruct_pat() recursively down until it hits `Pat::Const`
- Implement lowering `Pat::Range` into `IntRange`
- fix broken conversion logic between stored `BigInt` and `u128` representation (could be cleaned up)
- the type of the subject term should be passed into `deconstruct_pat` which fixes #462
- fixes problems with expansion of `or` patterns. fixes #468
> Exhaustiveness fixes

- compiler/hash-ast-passes/src/diagnostics/mod.rs
- compiler/hash-lexer/src/error.rs
- compiler/hash-parser/src/diagnostics/mod.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-reporting/src/diagnostic.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/mod.rs
- compiler/hash-typecheck/src/diagnostics/reporting.rs
- compiler/hash-typecheck/src/diagnostics/warning.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/range.rs
- compiler/hash-typecheck/src/exhaustiveness/usefulness.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/exhaustiveness.rs
- compiler/hash-typecheck/src/ops/mod.rs
- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-utils/src/store.rs
- tests/cases/exhaustiveness/non-exhaustive-decl.hash
- tests/cases/exhaustiveness/non-exhaustive-decl.stderr
- tests/cases/exhaustiveness/overlapping_range_ends.hash
- tests/cases/exhaustiveness/overlapping_range_ends.stderr
- tests/cases/exhaustiveness/simple_unreachable_pats.hash
- tests/cases/exhaustiveness/simple_unreachable_pats.stderr
- tests/runner.rs
- tests/testing-internal/src/metadata.rs
This patch introduces the ability for the typechecker to emit diagnostics that can either be errors or warnings. This patch does not attempt to change functions to follow a non-immediate failure pattern but allows for this pattern to be implemented. 
Additionally, as a proof of concept, the typechecker now emits `OverlappingRangeEnd`, `UselessMatchCase`, and `UnreachablePat` warnings across the typechecker.
closes #444
> Tc: diagnostics

- compiler/hash-ast-desugaring/src/visitor.rs
- compiler/hash-ast-passes/src/analysis/mod.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/diagnostics/warning.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-source/src/location.rs
- compiler/hash-token/src/lib.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/diagnostics/warning.rs
- compiler/hash-typecheck/src/exhaustiveness/construct.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/ops/params.rs
- compiler/hash-typecheck/src/ops/pats.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-utils/src/printing.rs
- tests/cases/exhaustiveness/non-exhaustive-constructor-field.stderr
- tests/cases/should_fail/types/unclose_type_args.stderr
- tests/cases/tc/structs/constructor-binds.hash
- tests/cases/tc/structs/missing-fields.stderr
This patch brings several fixes to reported locations in the reported terms.
- fix overwriting location when visiting variables, this should only occur for literal values.
- improve printing of sequences by introducing a `limit` term
- fix `term_of_pat` overwriting locations when it shouldn't
- fix validation of non-existent fields in constructor pattern validation
closes #456
> Tc: error reporting and bug fixes

- compiler/hash-alloc/src/collections/row.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/discover.rs
- compiler/hash-typecheck/src/ops/reader.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/storage/terms.rs
- compiler/hash-utils/src/printing.rs
- tests/testing-internal/src/metadata.rs
- tests/testing-macros/src/lib.rs
> tc: refactor `Term::{Merge|Union}` to use `TermListId`

- .github/workflows/rust.yml
Because there is no point and it is eating up valuable time.
> Do not build docs on CI

- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/pats.rs
- tests/cases/semantics/type_annotations/missing_struct_field_annotations.hash
- tests/cases/typecheck/spread-pats/tuple-spread-pats.hash
- tests/cases/typecheck/spread-pats/tuple-spread-pats.stderr
Something like:
```
test_all_spread := (f: (name: str, bax: char)) -> (name: str, bax: char) => {
(...t) := f;
t
};
```
no longer errors with "Not runtime instantiable"
> TC: Fix spread bug when the spread affects all tuple members and add test

- compiler/hash-ast/src/ast.rs
- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-source/src/location.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/location.rs
- compiler/hash-typecheck/src/storage/primitives.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-typecheck/src/traverse/scopes.rs
- tests/cases/typecheck/structs/missing-fields.stderr
- tests/cases/typecheck/traits/unspecified_member.hash
- tests/cases/typecheck/traits/unspecified_member.stderr
This patch improves the printing of large code blocks by collapsing intermediate lines with a `...`. This was initially entailed in #290 and is now implemented with this PR.
In order to test the implementation, the trait implementation validation logic was partially implemented, specifically the detection of methods present in the trait implementation that are not defined in the trait definition. partially completes #389 
This also fixes a bug with `visit_constant_scope` trying to take the declaration hint after it visits children which meant that the parent declaration hint was overwritten by the children before it could be used by the parent.
> reporting: minimalise report code blocks

- compiler/hash-typecheck/src/storage/mod.rs
- compiler/hash-typecheck/src/storage/nodes.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- tests/cases/typecheck/property_access/numeric_access_on_struct.stderr
- tests/cases/typecheck/property_access/out_of_bounds_access.stderr
- tests/cases/typecheck/spread-pats/tuple-spread-pats.stderr
- tests/cases/typecheck/structs/missing-fields.stderr
This PR adds a store `NodeInfoStore` which maps `AstNodeId`s to `TermId`s and `PatId`s. It is a necessary step for implementing mono/lowering to IR, as well as any post-TC semantic stages.
Closes #240.
> TC: Attach type information to nodes

- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/exhaustiveness/construct.rs
- compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
- compiler/hash-typecheck/src/exhaustiveness/fields.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/discover.rs
- compiler/hash-typecheck/src/ops/pats.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/storage/primitives.rs
This PR adds `NominalDef::Unit`. This is meant to be to constant enum variants what structs are to enum variants with data. Hopefully that makes sense. It is equivalent in spirit to a struct with an empty field list, or a simply a unit struct in rust `struct Foo;`.
In subsequent commits, this will be used to replace enums; enum variants will become either structs or units, depending on whether they have data members or not.
Closes #501.
> TC: Add unit nominal primitive

- compiler/hash-ast/src/ast.rs
- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-typecheck/src/traverse/operators.rs
- compiler/hash-typecheck/src/traverse/scopes.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/bootstrap.rs
- compiler/hash-types/src/builder.rs
- compiler/hash-types/src/lib.rs
- compiler/hash-types/src/storage.rs
- split `SkopeKind::Constant` into each specific variant of a constant scope kind. This is needed for checking the initialisation rules of declarations within constant scopes.
- verify that items cannot be declared as `mut` within constant blocks.
- verify that variables must be declared as `mut` for assign operations, and assigning operations with operators.
- closes #498
> tc: Implement traversal for assigning with operands

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/diagnostics/error.rs
- compiler/hash-parser/src/parser/block.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-tree-def/src/definitions.rs
- compiler/hash-tree-def/src/lib.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/lib.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- tests/cases/parser/types/enum_with_ty_params.hash
- tests/cases/parser/types/incomplete_ty_params.hash
- tests/cases/parser/types/incomplete_ty_params.stderr
- tests/cases/parser/types/struct_with_ty_params.hash
This pr enables the parser to accept the newly introduced syntax on the following constructs:
- nominal definitions, such as `struct`, `struct<T> { field: T }`
- trait definitions,
- `impl` blocks
- `mod` blocks
Additionally, this patch fixes a bug with the `parse_ty_params` not accounting for the "trailing comma" edge case.
Furthermore, this patch brings some missing documentation and fixes the recently introduced broken documentation links.
> lang: support type parameters on `{nominal:trait} defns, {impl:mod} blocks`

- compiler/hash-interactive/src/command.rs
- compiler/hash-interactive/src/lib.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/traits.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-vm/src/vm.rs
- compiler/hash-vm/tests/vm.rs
- compiler/hash/src/args.rs
- compiler/hash/src/main.rs
- tests/runner.rs
- VM: remove `InterpreterOptions` which are not currently needed.
- pipeline: remove `CompilerJobParams`, and propagate pipeline parameters via the pipeline settings.
- add `--dump-ast` for emitting the generated AST from the semantics/parser.
> pipeline: simplify pipeline settings and job parameter handling

- Cargo.lock
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-parser/src/parser/operator.rs
- compiler/hash-parser/src/parser/ty.rs
- tests/cases/parser/types/enum_with_ty_params.hash
This patch allows for the syntax `T -> U` where the left-hand side is a single argument to the function type.
> parser: arrow syntax improvements

- compiler/hash-ast-desugaring/src/desugaring.rs
- compiler/hash-ast-desugaring/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-parser/src/diagnostics/warning.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-parser/src/parser/ty.rs
- compiler/hash-typecheck/src/traverse/coerce.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-untyped-semantics/src/analysis/block.rs
- compiler/hash-untyped-semantics/src/diagnostics/directives.rs
- compiler/hash-untyped-semantics/src/visitor.rs
This is since Expr only contains an ExprKind field.
> Collapse ExprKind AST node to Expr

- compiler/hash-parser/src/parser/block.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/mod.rs
- tests/cases/parser/literals/dangling_parenthesis.stderr
- tests/cases/parser/misc/malformed_access_name.hash
- tests/cases/parser/misc/malformed_access_name.stderr
- tests/cases/parser/misc/malformed_function_literal_arrow.stderr
- tests/cases/parser/types/malformed_function_type.stderr
- tests/cases/parser/types/unclose_type_args.stderr
This patch removes the requirement for all expressions to have a `;` semi-colon present to signify the end of the expression. However, this does not mean that the parser does not support the semi-colon anymore. 
The semi-colon is still present and handled by the parser in order to terminate expressions. It is unclear if it should be removed entirely later, but it will be supported until there is some way to disambiguate unary operators and binary expressions.
> parser: remove `;` requirement after expressions

- compiler/hash-ast-desugaring/src/desugaring.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-parser/src/parser/block.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-untyped-semantics/src/visitor.rs
This is due to the renaming of a lot of AST nodes' fields from the PR #530.
> Simplify AST struct field destructuring by not renaming fields

- Cargo.lock
- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-expand/Cargo.toml
- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast-expand/src/visitor.rs
- compiler/hash-interactive/src/lib.rs
- compiler/hash-lower/Cargo.toml
- compiler/hash-lower/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/source.rs
- compiler/hash-pipeline/Cargo.toml
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/sources.rs
- compiler/hash-pipeline/src/traits.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-typecheck/Cargo.toml
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-untyped-semantics/src/diagnostics/warning.rs
- compiler/hash-untyped-semantics/src/lib.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- compiler/hash-vm/Cargo.toml
- compiler/hash-vm/src/vm.rs
- compiler/hash/src/args.rs
- compiler/hash/src/main.rs
- tests/cases/semantics/directives/unknown_directive.hash
- tests/cases/semantics/directives/unknown_directive.stderr
- tests/runner.rs
- tests/testing-internal/src/metadata.rs
- tests/testing-macros/src/lib.rs
This patch moves away from the `Compiler` using traits that implement abstract `Stage` interfaces and just to a single `CompilerStage`. This significantly simplifies the pipeline code and makes it more standard per stage.
> pipeline: use general `CompilerStage` for representing compiler stages

- Cargo.lock
- Cargo.toml
- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast-expand/src/visitor.rs
- compiler/hash-pipeline/src/sources.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-reporting/src/report.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-source/src/location.rs
- compiler/hash-typecheck/Cargo.toml
- compiler/hash/Cargo.toml
- compiler/hash/src/main.rs
- tests/Cargo.toml
- tests/runner.rs
This patch adds a new stage to the compiler called `hash-ast-expand` which will perform any expansions that need to happen for macros (which will be added in the future) or directives which are essentially a superset of macros, but allow the user to perform more powerful metaprogramming operations.
Addditionally, this patch refactors how line/column numbers are calculated, and where the logic is housed for this:
> Previously, when the compiler needed to convert `SourceLocation`s
and `Span`s into their respective row and columns values for line
number information, it was being done as a second thought in the
reporting sub-system.
> Now that there has been the need to access this logic from other crates,
it has been decided that this logic should live in `hash-source` and
be accessible by …
> ast-expand: `#dump_ast` directive now allows user to dump the AST for a particular expression

- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-untyped-semantics/src/analysis/block.rs
- compiler/hash-untyped-semantics/src/diagnostics/directives.rs
- compiler/hash-untyped-semantics/src/diagnostics/error.rs
- compiler/hash-untyped-semantics/src/diagnostics/origins.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- tests/cases/parser/misc/expresionless_directive.stderr
- tests/cases/semantics/directives/dump_ir.hash
- tests/cases/semantics/directives/dump_ir.stderr
> ir: add initial support for the `#dump_ir` directive

- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/ops/pats.rs
- tests/cases/patterns/548.hash
- tests/cases/patterns/548.stderr
- tests/cases/patterns/multiple_invalid_binds.hash
- tests/cases/patterns/multiple_invalid_binds.stderr
This patch fixes a problem with the error reporting for compound patterns that don't bind the same variables. This patch fixes this problem and improves the checking function to accumulate all errors in an instance and report them.
fixes #548
> TC: fix error reporting for non-equal compound pattern variable bounds

- compiler/hash-typecheck/src/traverse/scopes.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/nodes.rs
This PR adds the ability for AST nodes to have attached scopes, in the same way that they currently can have attached `TermId`s or `PatId`s. This is because scope information is required during code generation. The way to access `ScopeId`s is through the `NodeInfoStore` struct on `GlobalStorage`, by providing an `AstNodeId` as an input and retrieving a scope using the `scope_id` method on the resultant `NodeInfoTarget`.
The following nodes have scopes attached to them:
- `MatchCase`
- `BodyBlock`
- `TraitDef`
- `TraitImpl`
- `ModBlock`
- `ImplBlock`
- `Modules`
Therefore, it is only valid to call `scope_id` on `NodeInfoTarget`s accessed through an `AstNodeId` corresponding to one of the above AST nodes. (Otherwise there will be a panic.)
Closes #558
> Add the ability to assign `ScopeId`s to AST nodes

- compiler/hash-ast/src/ast.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/new/access.rs
- compiler/hash-types/src/new/args.rs
- compiler/hash-types/src/new/control.rs
- compiler/hash-types/src/new/data.rs
- compiler/hash-types/src/new/defs.rs
- compiler/hash-types/src/new/lits.rs
- compiler/hash-types/src/new/mod.rs
- compiler/hash-types/src/new/pats.rs
- compiler/hash-types/src/new/scopes.rs
- compiler/hash-types/src/new/terms.rs
- compiler/hash-types/src/new/tuples.rs
This PR completes the `pats` module of the new term structure. The pattern structure is simplified compared to the old structure. The notable differences are:
- The `Mod` pattern kind is not used anymore. Instead, module destructuring statements at constant scope level will be resolved to actual members during an AST traversal pass, so they do not need to be present in the term structure. This also removes the need to have `visibility` on `BindingPat`.
- The `Spread` pattern kind is not used anymore. Instead, list, tuple and constructor patterns have an optional `spread` field which records an index position and an optional name. It denotes that a spread pattern is present at the given position, with the given name. This is possible due to the invariant that spread patterns can only …
> Add patterns and literals to the new term structure.

- Cargo.lock
- compiler/hash-ast/src/ast.rs
- compiler/hash-ir/Cargo.toml
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/cfg.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-typecheck/src/exhaustiveness/constant.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-types/src/terms.rs
This patch introduces `IrTy` which is an enum that represents all of the types that can occur at the IR level. This enum is a simplified version of the `Term` structure that is used in the typechecking implementation.  This is introduced in order to avoid the complexities of dealing with the entire term structure during IR generation since only a part of the type term structure is present at the time of generation.
> IR: introduce `IrTy` to represent types at the IR level

- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/write.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-source/src/location.rs
- compiler/hash-typecheck/src/ops/pats.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/nodes.rs
This patch implements IR lowering for constant literals such as integers, floats, etc. Additionally, this patch also implements the handling of declarations that appear within body blocks.
> IR: lower primitive literal constants and declarations

- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/temp.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/cfg.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
This PR implements the lowering process for the following items:
- loops and constructs related to loops.
- return statements
- constant literal values
closes #581 
closes #576
> IR: lower `loop`, `break`, `continue` and `return` statements

- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
Currently, the typechecker cannot properly check the types of binary and unary expressions because the trait resolution system is not working properly and that the `prelude` does not contain trait definitions for these types. Once the new typechecking system is introduced by @kontheocharis, this issue will be fixed and this hack will be removed.
Relevant issue: https://github.com/hash-org/lang/issues/419
This patch is needed to implement: #574, #582
> typechecker: introduce workaround for currently broken trait resolution

- Cargo.lock
- Cargo.toml
- compiler/hash-pipeline/Cargo.toml
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-reporting/src/errors.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-target/Cargo.toml
- compiler/hash-target/src/lib.rs
- compiler/hash-typecheck/src/exhaustiveness/constant.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/range.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-types/Cargo.toml
- compiler/hash-types/src/storage.rs
- compiler/hash-types/src/terms.rs
- compiler/hash/Cargo.toml
- compiler/hash/src/args.rs
- compiler/hash/src/main.rs
This patch adds a new crate `hash-target` that contains all data structures that are needed for denoting which compilation target the compiler is emitting code for. There are two main data structures introduced:
- `Target` specifies the `point_width` in bytes and the name of the target (if applicable). It is likely that many more configurations/settings will be added to this struct.
- `TargetInfo` which specifies the `target` to which we are compiling, and `host` which is the host machine of the compiler represented as a `Target`. The `host` variant will be needed later for compile-time execution/VM operations.
Additionally, this patch integrates `pointer_width` based on the compilation target when computing the size, minimum and maximum values of `isize` and `usize` in `hash-source` and …
> pipeline: introduce `Target` to denote what compilation target the compiler is compiling to

- Cargo.lock
- compiler/hash-ast/src/ast.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-lower/Cargo.toml
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/category.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/temp.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-typecheck/src/ops/discover.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/substitute.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/traverse/operators.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/bootstrap.rs
- compiler/hash-types/src/builder.rs
- compiler/hash-types/src/terms.rs
This patch implements lowering for the following items:
- binary operators (with addition of `CheckedOp`)
- basic constant folding
- unary operators
- function calls
- index expressions and assignments
- field expressions and assignments
closes #580 
closes #574 
closes #582
> lower: implement `{binary+unary}` operators, function calls, indexing, field access 

- Cargo.lock
- compiler/hash-ast/src/ast.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-lexer/Cargo.toml
- compiler/hash-lexer/src/error.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-lower/Cargo.toml
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/matches.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-parser/src/diagnostics/error.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-source/Cargo.toml
- compiler/hash-source/src/constant.rs
- compiler/hash-target/src/lib.rs
- compiler/hash-target/src/size.rs
- compiler/hash-typecheck/src/exhaustiveness/constant.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/exhaustiveness/range.rs
- compiler/hash-typecheck/src/exhaustiveness/wildcard.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-types/src/pats.rs
- compiler/hash-types/src/terms.rs
- compiler/hash/src/args.rs
This patch re-works `IntConstant` to store the `IntTy` on each constant so that it can be accessed across all users of the value. This has simplified some code and has changed some responsibilities (from the parser to the lexer). More specifically, when literals have suffixes, it is now the lexer's job to verify that they are valid suffixes instead of letting this be dealt with later at the parsing stage.
Furthermore, this adds some of the beginnings of the lowering process for `match` expressions. The procedure is as follows:
- firstly, we convert all the match arms into `Candidate`s which store information about the binds that occur in each arm, whether they have an `if_guard` etc, and the blocks they will jump. (done)
- next, all the `Candidate`s are flattened since patterns may have …
> source: re-work constants and start lowering `match`es

- compiler/hash-pipeline/src/lib.rs
- compiler/hash-reporting/src/builder.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/new/diagnostics/error.rs
This commit adds the `Reporter` struct to the `reporting` crate. This struct is used to create a `Vec<Report>` from `ReportBuilder`s which are created using `add_report()`.
> Add `Reporter` to `reporting` crate to create `Vec<Report>` easily

- Cargo.lock
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-pipeline/Cargo.toml
- compiler/hash-pipeline/src/fs.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-typecheck/src/exhaustiveness/construct.rs
- compiler/hash-typecheck/src/exhaustiveness/deconstruct.rs
- compiler/hash-typecheck/src/exhaustiveness/fields.rs
- compiler/hash-typecheck/src/exhaustiveness/lower.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/ops/pats.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/typing.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-types/src/builder.rs
- compiler/hash-types/src/nominals.rs
- compiler/hash-types/src/terms.rs
- tests/cases/typecheck/enums/basic.hash
- tests/runner.rs
This patch implements partial support for `enum`s within exhaustiveness checking. In particular, the lowering process of `enum` variant patterns has been implemented to convert them into `DeconstructedCtor::Variant`, and then let the core of the algorithm check exhaustiveness. In order to make this change work, there was an adjustment from converting `EnumDef`s into `Unit` definitions, and rather into the old `Enum` format since most of the code was already purposed for this representation. When the new type-checking is stable and implemented, this will need to be migrated (albeit it should be easier to migrate to the new representation since the initial work has been done).
Additionally:
- this fixes a bug with bootstrapping process of the compiler on Windows where the `prelude.hash` …
> tc+exhaustiveness: add partial support for exhaustiveness checking for `enum`s

- compiler/hash-error-codes/src/error_codes.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/pat.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/temp.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-lower/src/cfg.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
This patch allows for constructors, tuples, and arrays as `RValue`s. Additionally, this patch makes `Place` store projections in a `projection_store` to make `Place` copyable and smaller when being passed around during the lowering stage.
closes #578 
closes #612 
closes #579 
closes #618
> lowering: support lowering `enum`, `struct`, `(a, b)` and `[a, b, c]` as `RValue`s

- compiler/hash-ast/src/ast.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-token/src/lib.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- tests/cases/parser/literals/overeager_tuple_lit_entry.hash
This patch introduces proper handling of a logical operator (`&&` and `||`) short-circuiting properties during IR generation.
Additionally,
- fix parser bug with over-eager tuple parsing, when expressions like `(x == ...)` are encountered.
- don't lower the subject of a `match` block that originates from an `if` expression.
- typechecker: properly type binary expressions that yield a boolean result.
closes #617
> lower: correctly handle logical operator short-circuiting

- compiler/hash-ir/src/basic_blocks.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write/graphviz.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-ir/src/write/pretty.rs
- compiler/hash-lexer/src/utils.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-lower/src/optimise/mod.rs
- compiler/hash-lower/src/optimise/simplify.rs
- compiler/hash-lower/src/traversal.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-session/src/lib.rs
- compiler/hash/src/args.rs
This patch introduces a new stage to the lowering pipeline responsible for orchestrating optimisations on the IR. The first implementation is not currently sophisticated and cannot be parallelised, however, it is a good starting point for the future when considering this problem.
The first pass implemented is a simplification pass which trims dead blocks from the graph and removes redundant jump chains. There are many other possible and more sophisticated optimisations that can be performed on the IR before code generation, however, this commit is a good starting point for future work.
The next step to adding more optimisations is creating an IR visitor that can walk the IR mutably for simplifying and re-writing the IR, and immutably (for later stages of code generation).
closes #588
> lowering: introduce a optimisation pass manager for the IR

- compiler/hash-typecheck/src/new/ops/fns.rs
- compiler/hash-typecheck/src/new/ops/mod.rs
- compiler/hash-typecheck/src/new/ops/mods.rs
- compiler/hash-typecheck/src/new/ops/params.rs
- compiler/hash-typecheck/src/new/passes/scope_discovery.rs
- compiler/hash-types/src/new/mods.rs
This PR adds code to traverse function definitions during scope discovery and add them to the storage. At this stage, all types and terms are left as holes, and will be resolved further down the line when all the declarations have been discovered.
Closes #601
> Traverse functions and blocks in scope discovery

- compiler/hash-typecheck/src/new/ops/data.rs
- compiler/hash-typecheck/src/new/ops/params.rs
- compiler/hash-typecheck/src/new/passes/scope_discovery.rs
This PR adds discovery for struct and enum definitions. These are converted into data definitions.
The following snippet:
```
Lin := mod {
Fing := struct <A, B, C> (foo: i32, bar: str, baz: char)
Zing := enum <X, Y, Z> (Red(u8), Blue, Green(a: str, b: i32))
}
```
now produces the definitions:
```
Lin := mod [name=Lin, type=block]  {
Fing := datatype [name=Fing] <A: Hole8, B: Hole9, C: Hole10> {
Fing: (foo: Hole11, bar: Hole12, baz: Hole13) -> Fing<A, B, C>
}
Zing := datatype [name=Zing] <X: Hole14, Y: Hole15, Z: Hole16> {
Red: (s25: Hole17) -> Zing<X, Y, Z>
Blue: Zing<X, Y, Z>
Green: (a: Hole18, b: Hole19) -> Zing<X, Y, Z>
}
}
```
Closes #604
> Implement scope discovery for structs and enums

- compiler/hash-typecheck/src/new/diagnostics/error.rs
- compiler/hash-typecheck/src/new/passes/scope_discovery.rs
Since the new typechecker does not currently support traits, it doesn't make sense for it to support merge declarations, so this PR adds an error message when a merge declaration is encountered.
#626 should be merged first.
Closes #627
> Add unsupported error message for merge declarations

- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-utils/src/store.rs
- compiler/hash/src/args.rs
This patch adds new IR visitors that are able to traverse the generated IR with the following parameters:
- a visitor with a mutable context, but immutable read the IR
- a visitor with an immutable context, but mutably walk the IR
The current visitor implementation is written by hand (and it is quite ugly, especially the `modify`s), and I solemnly promise to create a macro for the visitor and walking code for the following attributes:
- a visitor with a mutable context, immutably walk the IR
- a visitor with an immutable context, immutably walk the IR
- a visitor with a mutable context, mutably walk the IR
- a visitor with an immutable context, mutably walk the IR
Furthermore, it would be nice to find a way to avoid constantly `modify`ing the IR (since it is a `clone()`) but attempts to …
> IR: implement a basic visitor for mutable context, and a modifying visitor

- Cargo.lock
- compiler/hash-utils/Cargo.toml
- compiler/hash-utils/src/store.rs
This new store uses [`append_only_vec`](https://docs.rs/append-only-vec/latest/append_only_vec/) instead of a `RefCell<Vec<_>>` in order to allow modification of elements without needing to clone anything. It basically allows you to get a `&Cell<Value>` reference, instead of having to map over a value using a closure.
The stores should also eventually be moved to `hash-alloc` because that makes more semantic sense, though this PR does not address this yet.
> Add a `CellStore` to avoid unnecessary clones with stores

- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/cfg.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-lower/src/optimise/simplify.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/cache.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/storage/cache.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-utils/src/store.rs
This patch makes the `RValue` tree simpler by introducing the notion of an `Operand`, which is essentially the leaf of an `RValue` tree. Introducing this item will do the following:
- reduce the number of `RValue`s created overall.
- simplify and improve the performance of traversals that may modify the IR as they go.
- This patch also greatly improves the performance of the `simplify_graph` pass making it run in about `<1ms`, where as previously it was taking `~550ms` for a particular test case. This optimisation was achieved by keeping an in-place up-to-date record of graph block predecessors when eliminating `goto` chains.
- fix bug where `reached_terminator` wasn't being reset in `Builder` causing all future blocks to not be lowered.
- Is the whole …
> ir+lowering improvements

- Cargo.lock
- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast/Cargo.toml
- compiler/hash-ast/src/node_map.rs
- compiler/hash-interactive/src/lib.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/source.rs
- compiler/hash-pipeline/src/interface.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/workspace.rs
- compiler/hash-source/Cargo.toml
- compiler/hash-source/src/lib.rs
- compiler/hash-typecheck/src/traverse/visitor.rs
- compiler/hash-untyped-semantics/src/lib.rs
- compiler/hash-vm/src/stack.rs
This patch simplifies the logic of how sources are identified within the compiler, and significantly cuts down on the memory usage of the representation. Previously, the `SourceId` was defined as:
```rs
enum SourceId {
Module(ModuleId),
Interactive(InteractiveId)
}
```
with each sub-id being 8 bytes (which is too big) in size. This design is somewhat wasteful because it forces `SourceId` to be aligned to 12 bytes. Now, `SourceId` is
defined as the following:
```rs
struct SourceId {
_raw: u32
}
```
This `_raw` value uses the leftmost bit to represent the kind of source it is (either `module` or `interactive`), and the rest of the bits are used to describe the Id of the actual source. This is a reasonable size reduction because the compiler isn't expecting the total amount of sources to …
> source: Shrink `SourceId` from 12 bytes to 4 bytes

- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/new/environment/tc_env.rs
- compiler/hash-typecheck/src/new/ops/bootstrap.rs
- compiler/hash-typecheck/src/new/ops/common.rs
- compiler/hash-typecheck/src/new/ops/context.rs
- compiler/hash-typecheck/src/new/ops/data.rs
- compiler/hash-typecheck/src/new/ops/mod.rs
- compiler/hash-typecheck/src/new/ops/normalise.rs
- compiler/hash-typecheck/src/new/passes/scope_discovery.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/exprs.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/mod.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/params.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/paths.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/pats.rs
- compiler/hash-typecheck/src/new/passes/symbol_resolution/tys.rs
- compiler/hash-types/src/new/access.rs
- compiler/hash-types/src/new/args.rs
- compiler/hash-types/src/new/data.rs
- compiler/hash-types/src/new/lits.rs
- compiler/hash-types/src/new/locations.rs
- compiler/hash-types/src/new/mods.rs
- compiler/hash-types/src/new/params.rs
- compiler/hash-types/src/new/pats.rs
- compiler/hash-types/src/new/scopes.rs
- compiler/hash-types/src/new/terms.rs
- compiler/hash-types/src/new/tys.rs
- compiler/hash-utils/src/store.rs
This PR adds functionality to inject primitive definitions (numbers, bool, char, str, list, option, etc) into the context, which is needed for completing resolution (subsequent PR). It also reorganises parameter-related utilities for resolution into its own module. Some TC-related scaffolding is also added, namely normalisation. Finally, vars are now just `Symbol` rather than `BoundVar`, because the rest of the info can be deduced from the context. 
Closes #667 
Fixes #665
> Add bootstrapping primitives to TC

- compiler/hash-typecheck/src/new/ops/common.rs
- compiler/hash-typecheck/src/new/ops/context.rs
- compiler/hash-typecheck/src/new/ops/params.rs
- compiler/hash-typecheck/src/new/passes/ast_utils.rs
- compiler/hash-typecheck/src/new/passes/discovery/defs.rs
- compiler/hash-typecheck/src/new/passes/discovery/params.rs
- compiler/hash-typecheck/src/new/passes/discovery/visitor.rs
- compiler/hash-typecheck/src/new/passes/resolution/exprs.rs
- compiler/hash-typecheck/src/new/passes/resolution/scoping.rs
- compiler/hash-typecheck/src/new/passes/resolution/tys.rs
- compiler/hash-types/src/new/environment/context.rs
- compiler/hash-types/src/new/terms.rs
- compiler/hash-types/src/new/tys.rs
This PR is the same as #676, but for types. Now all type annotations in the AST get resolved. Any remaining holes will be filled by unification at a later stage.
Closes #680
> Resolve AST types during resolution

- compiler/hash-codegen/src/common.rs
- compiler/hash-codegen/src/lib.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-codegen/src/traits/constants.rs
- compiler/hash-codegen/src/traits/ty.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/ty.rs
This patch implements the lowering procedures for all `RValue` kinds.
> codegen: implement lowering `RValue`s

- compiler/hash-codegen/src/common.rs
- compiler/hash-codegen/src/lower/constants.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/lower/statement.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/lower/utils.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-codegen/src/traits/constants.rs
- compiler/hash-codegen/src/traits/ctx.rs
- compiler/hash-codegen/src/traits/layout.rs
- compiler/hash-codegen/src/traits/mod.rs
- compiler/hash-codegen/src/traits/ty.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/layout.rs
- compiler/hash-target/src/size.rs
This patch implements handling of code generation for `Operand`, and places (including all projections that can occur on a `Place`).
This means that all of the code to convert IR into backend IR (#649) is now complete, which means now the next things to tackle are:
- computing type layouts (#646)
- checking the semantics of the entry point (#647)
- figure out how we glue everything together at the end (#651) i.e. linking
closes #649
> codegen: handle code generation for operands and places

- Cargo.lock
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-target/Cargo.toml
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/layout.rs
- compiler/hash-target/src/lib.rs
- compiler/hash-target/src/primitives.rs
- compiler/hash-target/src/size.rs
This PR implements all of the logic responsible for computing a type's layout. 
The basic algorithm for struct-like (univariant) types is to essentially sort the fields by the following rules:
- push all of the ZST-like fields to the start of the struct to avoid dealing with them between other fields
- sort the remaining fields in order of "effective" alignment of each field, essentially the largest fields by
size and alignment are grouped first, and then descending down. 
- try and optimise the ABI of the given type to represent it as a scalar which means it can reach more 
optimisations when code is generated for this kind.
For enum ADTs, the algorithm is the following:
- Compute the layout of the enum tag
- Compute the layout of the inner ADT of each enum variant with the provided enum …
> layout: implement computing the layout for all `IrTy`s

- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/primitives.rs
This patch implements the missing functionality of deducing types from IR constructs like `RValue`s, `Place`s, `Operand`s. 
Additionally, this implements missing functionality within `hash-layout`, specifically logic for computing the layout of a field within a type.
> codegen+ir: tie up loose ends and un-implemented items

- compiler/hash-ast/src/tree.rs
- compiler/hash-backend/src/lib.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/matches/utils.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/ty/mod.rs
- compiler/hash-reporting/src/macros.rs
- compiler/hash-session/src/lib.rs
This patch fixes a bug with `bool` patterns not being lowered within the match jump table construction logic. 
Additionally, this patch does the following:
- fixes a printing of integer/float literal in the AST, since their suffix was being printed twice.
- introduces `compiler_note!` macro for emitting a _note_ for a given span, which is useful for
debugging things that have a `Span` on them.
> lowering: fix bug with `bool` literals in `match` cases not being handled

- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-layout/src/write.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/category.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/const_range.rs
- compiler/hash-lower/src/build/matches/declarations.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/temp.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-lower/src/optimise/mod.rs
- compiler/hash-lower/src/optimise/simplify.rs
- compiler/hash-target/src/primitives.rs
This patch ensures that all AST items references in the lowering and IR logic are prefixed with `ast::` to disambiguate whether it is an AST item or an IR item.
Furthermore, this patch brings a small improvement to layout visualisation which removes the "ghost" padding for enum variants, and aligns the enum variant labels with the tag box for clarity.
> layout+lower: improvements and documentation clean

- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/lower/utils.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-layout/src/write.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/optimise.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-source/src/constant.rs
This patch implements emitting checked operations for unary negation overflow and division/remainder by zero.
Additionally, this patch implements missing logic for computing the type of `RValue`s.
> lowering: implement emitting overflow checks for unary ops and `BinOp::Div` and `BinOp::Mod`

- compiler/hash-abi/src/lib.rs
- compiler/hash-codegen/src/lower/abi.rs
- compiler/hash-codegen/src/lower/mod.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/lower/utils.rs
- compiler/hash-codegen/src/traits/ctx.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/data_layout.rs
- compiler/hash-target/src/lib.rs
- compiler/hash-target/src/primitives.rs
- compiler/hash-target/src/size.rs
This patch implements logic for parsing data layout strings, and some basic logic to compute the `FnAbi` of a function. The logic to compute `FnAbi`s is missing a lot of features and currently doesn't support annotating functions with potentially different ABIs which is something we should look into in the future (possibly with directives or additional syntax like `extern <abi> func := () => { ... }`.
> abi+layout: implement ABI deduction and parsing data layouts

- compiler/hash-semantics/src/new/ops/bootstrap.rs
- compiler/hash-semantics/src/new/ops/infer.rs
- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-semantics/src/new/passes/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/mod.rs
- compiler/hash-tir/src/new/environment/context.rs
This PR adds the final step of inference to the typechecking pipeline, All this does is just infer the term or module corresponding to the node, and then print the result.
Note that the typechecking is still not quite functional yet, there are some bits left to implement: substitutions, hole filling, (normalisation).
Closes #708
> Hook up typechecking to the semantic pipeline

- Cargo.lock
- compiler/hash-abi/src/lib.rs
- compiler/hash-codegen-llvm/src/translation/abi.rs
- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/context.rs
- compiler/hash-codegen-llvm/src/translation/declare.rs
- compiler/hash-codegen-llvm/src/translation/intrinsics.rs
- compiler/hash-codegen-llvm/src/translation/layouts.rs
- compiler/hash-codegen-llvm/src/translation/metadata.rs
- compiler/hash-codegen-llvm/src/translation/mod.rs
- compiler/hash-codegen-llvm/src/translation/ty.rs
- compiler/hash-codegen/src/common.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-codegen/src/traits/ty.rs
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/primitives.rs
This PR is an initial progress checkpoint on implementing all of the required code generation methods for the LLVM backend. This patch implements all of the methods in `BlockBuilderMethods`. The next things to implement are the `BuildConstValueMethods` and `BuildTypeMethods`.
> codegen(llvm): implement all `BlockBuilderMethods` on `Builder`

- compiler/hash-abi/src/lib.rs
- compiler/hash-codegen-llvm/src/translation/misc.rs
- compiler/hash-codegen/src/lower/abi.rs
- compiler/hash-target/src/abi.rs
- compiler/hash-target/src/lib.rs
This patch implements the remaining functionality that is needed for fully completing the code generation side of the LLVM backend.
> codegen(llvm): implement code generating a program entry point

- compiler/hash-intrinsics/src/primitives.rs
- compiler/hash-intrinsics/src/utils.rs
- compiler/hash-semantics/src/new/diagnostics/error.rs
- compiler/hash-semantics/src/new/passes/discovery/params.rs
- compiler/hash-semantics/src/new/passes/discovery/visitor.rs
- compiler/hash-semantics/src/new/passes/resolution/params.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/pats.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-tir/src/new/data.rs
- compiler/hash-tir/src/new/defs.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/environment/stores.rs
- compiler/hash-tir/src/new/locations.rs
- compiler/hash-tir/src/new/params.rs
- compiler/hash-tir/src/new/pats.rs
- compiler/hash-tir/src/new/tuples.rs
- compiler/hash-tir/src/new/utils/common.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-tir/src/new/utils/data.rs
- compiler/hash-tir/src/new/utils/defs.rs
- compiler/hash-tir/src/new/utils/params.rs
- compiler/hash-tir/src/new/utils/traversing.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
Before, data types could contain multiple groups of parameters like `<T: Type> (t: T) ...`. This has been removed to simplify the implementation, since even the simple `Params` etc will allow for dependent referencing (e.g. `(T: Type, t: T)`). Now data types are only annotated with a single`<...>` parameter list. This also should cut down on memory usage, and nicely shaves off almost 1k lines of boilerplate.
Closes #755
> Remove DefParams/DefArgs/DefPatArgs in favour of the simple versions

- compiler/hash-semantics/src/new/passes/discovery/defs.rs
- compiler/hash-semantics/src/new/passes/discovery/visitor.rs
- compiler/hash-semantics/src/new/passes/resolution/defs.rs
- compiler/hash-semantics/src/new/passes/resolution/exprs.rs
- compiler/hash-semantics/src/new/passes/resolution/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/params.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/scoping.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/unification.rs
This PR adds the ability to resolve tuples like `(T: Type, t: T)`. This also works for constructor parameters, data parameters, and function parameters.
Closes #758
> Resolve dependent tuple members

- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-typecheck/src/inference.rs
As a prerequisite to dependent type checking, this PR adds an equality judgement to the context, so that the typechecker can keep track of terms which are equal.
Closes #757 
Merge #759 first.
> Add an equality judgement

- compiler/hash-semantics/src/new/diagnostics/error.rs
- compiler/hash-semantics/src/new/passes/discovery/defs.rs
- compiler/hash-semantics/src/new/passes/discovery/visitor.rs
- compiler/hash-semantics/src/new/passes/resolution/defs.rs
- compiler/hash-semantics/src/new/passes/resolution/exprs.rs
- compiler/hash-semantics/src/new/passes/resolution/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/params.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/pats.rs
- compiler/hash-semantics/src/new/passes/resolution/scoping.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/scopes.rs
- compiler/hash-tir/src/new/terms.rs
- compiler/hash-tir/src/new/utils/common.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-tir/src/new/utils/stack.rs
- compiler/hash-tir/src/new/utils/traversing.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/unification.rs
- compiler/hash-utils/src/store.rs
This PR allows definitions to be present in blocks `{}`, which means that definitions can now exist in interactive mode as well. It is ensured that inside these definitions nothing is accessed that is declared in a runtime context.
This PR also adds some initial normalisation code, to be completed in subsequent PRs.
Closes #706
> Allow definitions in runtime blocks, and partially implement normalisation

- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/intrinsics.rs
- compiler/hash-codegen-llvm/src/translation/metadata.rs
- compiler/hash-codegen-llvm/src/translation/ty.rs
- compiler/hash-codegen/src/lower/block.rs
- compiler/hash-codegen/src/lower/mod.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-ir/src/basic_blocks.rs
- compiler/hash-ir/src/intrinsics.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/mod.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/ty/mod.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-utils/src/graph/dominators.rs
- compiler/hash-utils/src/graph/mod.rs
- compiler/hash-utils/src/graph/tests/mod.rs
- compiler/hash-utils/src/graph/visit.rs
- compiler/hash-utils/src/lib.rs
- compiler/hash/src/main.rs
This patch is just a general bug fixing patch with emitted LLVM IR, layout information, and the entry point not being registered, amongst other things.
However, this is the first PR that enabled the Hash compiler to emit some machine code!
> codegen: some fixes with code generation and layout info

- Cargo.lock
- compiler/hash-ast-expand/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-backend/src/lib.rs
- compiler/hash-codegen-llvm/Cargo.toml
- compiler/hash-codegen-llvm/src/context.rs
- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/intrinsics.rs
- compiler/hash-codegen-llvm/src/translation/ty.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-semantics/src/traverse/visitor.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- tests/cases/semantics/directives/unknown_directive.stderr
This patch fixes the following issues:
- `load_operand` wasn't dealing with loading immediates (i.e. `bool`) correctly, and converting them into `i8`s where an `i1` was expected.
- `size_ty` wasn't being correctly initialised with the correct integer width.
- fix interactive start-up crash with the LLVM backend.
- fix directive errors being reported in a non-deterministic order.
> codegen: several fixes

- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/exprs.rs
- compiler/hash-semantics/src/new/passes/resolution/pats.rs
- compiler/hash-tir/src/new/control.rs
- compiler/hash-tir/src/new/lits.rs
- compiler/hash-tir/src/new/pats.rs
- compiler/hash-tir/src/new/scopes.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-tir/src/new/utils/traversing.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
Closes #673. For now interactive normalises its output. There are still some bugs to fix (next PRs)
```rs
>>> (a, b) := ((foo: i32) => (foo, (foo, () -> i32 => foo)))(3); b
(3_i32, () -> i32 => 3_i32)
```
> Implement normalisation of TIR terms

- compiler/hash-semantics/src/new/passes/discovery/defs.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/pats.rs
- compiler/hash-semantics/src/new/passes/resolution/scoping.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/scopes.rs
- compiler/hash-tir/src/new/utils/common.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-tir/src/new/utils/stack.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
This PR addresses the following issues:
- Pattern binds in match cases were added to the scope but the scope was exited before the case was run
- Stack members stored their values, rather than the context, which doesn't work if the same stack appears in the context multiple times (recursion, loops, etc)
Closes #767.
> Fix some normalisation bugs

- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/params.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/scoping.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-tir/src/new/environment/context.rs
- compiler/hash-tir/src/new/sub.rs
- compiler/hash-tir/src/new/utils/common.rs
- compiler/hash-tir/src/new/utils/context.rs
- compiler/hash-tir/src/new/utils/traversing.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
This PR follows from #731 by fixing a few bugs and implements inference of constructor type arguments. Now, `Option<_>::Some(3)` is typed as `Option<i32>`. This is currently not implemented for arbitrary functions, just constructors.
There are still a few bugs to fix but now the type-checker is able to check and run a lot of programs! (mod the unimplemented stuff)
> Fix some inference bugs and implement constructor type argument inference

- compiler/hash-intrinsics/src/primitives.rs
- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-tir/src/new/utils/common.rs
- compiler/hash-tir/src/new/utils/data.rs
- compiler/hash-tir/src/new/utils/params.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
Inference now works fully for implicit arguments:
```
foo := <T> => (t: T) => Option::Some(t); 
bar := foo(3) // bar : Option<i32>
```
Closes #737, closes #778
> Implement implicit argument inference for function calls and constructors

- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-ir/src/mod.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-layout/src/write.rs
This patch fixes two issues in layout and codegen logic:
- arguments that should be passed as scalar pairs not being properly handled. 
- layout label of "ZST" for visualization is unclear - fixed by adding the type that is the ZST
> codegen+layout: fix issue with string literals not being dealt with properly.

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-parser/src/parser/ty.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-semantics/src/traverse/visitor.rs
- compiler/hash-token/src/keyword.rs
- tests/cases/parser/literals/map_literals.hash
- tests/cases/parser/literals/set_literals.hash
- tests/cases/parser/types/enum_with_ty_params.hash
- tests/cases/parser/types/struct_with_ty_params.hash
This patch removes the parser and typechecking logic that tries to explicitly deal with map and set literals, and map//set types. Since they weren't being implemented in the new typechecking or the AST lowering, it was decided that they should be removed (for now) for code housekeeping.
> language: remove `map` and `set` syntax from the language for now

- compiler/hash-semantics/src/new/diagnostics/error.rs
- compiler/hash-semantics/src/new/passes/ast_utils.rs
- compiler/hash-semantics/src/new/passes/discovery/mod.rs
- compiler/hash-semantics/src/new/passes/discovery/params.rs
- compiler/hash-semantics/src/new/passes/discovery/visitor.rs
- compiler/hash-semantics/src/new/passes/resolution/exprs.rs
- compiler/hash-semantics/src/new/passes/resolution/paths.rs
- compiler/hash-semantics/src/new/passes/resolution/tys.rs
- compiler/hash-typecheck/src/inference.rs
Also, shorthand struct syntax `Dog()` instead of `Dog::Dog()`.
> Add better inference for numeric literals and some resolution bug fixes

- compiler/hash-codegen-llvm/src/translation/constants.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/ty/mod.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-parser/src/source.rs
- compiler/hash-semantics/src/exhaustiveness/constant.rs
- compiler/hash-semantics/src/exhaustiveness/lower.rs
- compiler/hash-semantics/src/exhaustiveness/range.rs
- compiler/hash-semantics/src/ops/typing.rs
- compiler/hash-semantics/src/ops/validate.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-target/src/primitives.rs
- compiler/hash-tir/src/new/lits.rs
- compiler/hash-tir/src/terms.rs
This PR refactors the handling of integer constants within the compiler to just use integer slots rather than storing them as a singular scalar and converting between one and the other.
> source: refactor `IntConstant` to use value slots rather than scalar

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-tir/src/new/args.rs
- compiler/hash-tir/src/new/atom_info.rs
- compiler/hash-tir/src/new/environment/stores.rs
- compiler/hash-tir/src/new/fns.rs
- compiler/hash-tir/src/new/mod.rs
- compiler/hash-tir/src/new/utils/mod.rs
- compiler/hash-tir/src/new/utils/mods.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/unification.rs
This PR adds `AtomInfoStore`, available to `AccessToEnv`. This stores the inferred type of each term, as well as its "resolved" version. You can use it like
```rs
t: TermId or PatId or ArgsId or PatArgsId or TyId
self.get_inferred_ty(t) // : TyId or ParamsId (depending on what t is)
self.get_inferred_value(t) // : typeof t
```
There are also fallible equivalents. See `ItemInAstInfo` trait.
Closes #743
> Add AtomInfo store to store inference of terms to their types

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-semantics/src/passes/resolution/defs.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-tir/src/directives.rs
- compiler/hash-tir/src/environment/stores.rs
- compiler/hash-tir/src/lib.rs
- compiler/hash-tir/src/mod.rs
This PR adds the ability to access directives on TIR terms, functions, data defs, patterns, params, and types. This is accessed through `AppliedDirectivesStore`, which indexes a list of directive names by a directive target (one of the above).
> Track directives in the TIR

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-semantics/src/lib.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-semantics/src/passes/resolution/tys.rs
- compiler/hash-tir/src/args.rs
- compiler/hash-tir/src/atom_info.rs
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-tir/src/utils/traversing.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
This PR traverses functions in two passes, first to resolve their types and then to resolve their bodies. This allows for recursive calls to work. Furthermore, normalisation of typeof should work better.
> Fix some issues with normalisation and recursive inference

- compiler/hash-tir/src/locations.rs
This bug is due to the usage of `BiMap`. Adding `(k1, v)` when there already exists `(k2, v)` will delete the latter. Location mappings shouldn't really be bijective, so we can just use a regular `HashMap`.
> Fix bug where locations get unset when adding duplicate entries

- compiler/hash-lower/src/build/ty.rs
- compiler/hash-tir/src/utils/traversing.rs
Functions should only be f-mapped if they are not intrinsic.
> Do not fmap functions that are intrinsic

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-intrinsics/src/primitives.rs
- compiler/hash-intrinsics/src/utils.rs
- compiler/hash-lower/src/build/category.rs
- compiler/hash-lower/src/build/constant.rs
- compiler/hash-lower/src/build/expr.rs
- compiler/hash-lower/src/build/matches/declarations.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/ty/mod.rs
- compiler/hash-semantics/src/passes/discovery/defs.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-semantics/src/passes/resolution/tys.rs
- compiler/hash-tir/src/access.rs
- compiler/hash-tir/src/arrays.rs
- compiler/hash-tir/src/data.rs
- compiler/hash-tir/src/lib.rs
- compiler/hash-tir/src/lits.rs
- compiler/hash-tir/src/pats.rs
- compiler/hash-tir/src/scopes.rs
- compiler/hash-tir/src/terms.rs
- compiler/hash-tir/src/utils/traversing.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/unification.rs
This PR adds basic typechecking for these constructs. There are still a few small issues to fix but this should be sufficient for the lowering to be able to deal with these terms. Subsequent PRs will perform further cleanup of some of the inference code and factor out common patterns. Additionally, more sophisticated unification will be added.
Closes #777
> Implement typechecking of matches, arrays, indexing, assign terms

- compiler/hash-intrinsics/src/utils.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
A block term is now always added to the loop contents, independently of what the AST looks like.
> Fix desugared loops resolution

- compiler/hash-interactive/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/args.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-semantics/src/environment/sem_env.rs
- compiler/hash-semantics/src/lib.rs
- compiler/hash-semantics/src/old/mod.rs
- compiler/hash-semantics/src/passes/ast_utils.rs
- compiler/hash-semantics/src/passes/evaluation/mod.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-semantics/src/passes/mod.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-tir/src/atom_info.rs
- compiler/hash-tir/src/directives.rs
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-untyped-semantics/src/lib.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- compiler/hash-utils/src/store.rs
- tests/runner.rs
- tests/testing-internal/src/metadata.rs
This PR adds:
- The ability to use `run` with a file in order to run it in the TIR evaluator.
- Interactive mode using the evaluator by default.
- `#dump_tir` directive to dump TIR of specific types and terms
- `-Cdump=tir` flag to dump TIR of all modules and interactive blocks
> Properly integrate the new semantic analysis with the compiler pipeline

- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-ir/src/cast.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-tir/src/fns.rs
- stdlib/prelude.hash
This PR implements the casting intrinsic which allows for primitive types to be converted between one and the other.
closes #645
> lower+codegen: implement casting operations for primitive types

- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/statement.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-ir/src/write/pretty.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/ty/mod.rs
This PR fixes an issue with function arguments being placed into scope when they shouldn't be. This caused the scoping to fail when attempting to resolve variables that were referenced in function call arguments.
Additionally, this PR introduces  `Live` and `Dead` statements in order to denote liveness intervals for locals that are declared in the body. Whilst liveness isn't implemented yet, this is one of the needed components for this.
> lower+ir: fix issue with fn scoping args and add `Live` and `Dead` statement variants

- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/debug_info.rs
- compiler/hash-codegen-llvm/src/translation/ty.rs
- compiler/hash-codegen/src/lower/intrinsics.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/build/matches/declarations.rs
- compiler/hash-lower/src/build/matches/mod.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/lower_ty.rs
- compiler/hash-lower/src/ty/mod.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-target/src/abi.rs
- stdlib/prelude.hash
This patch fixes the handling of string and slice types within code generation. This patch also implements the `Intrinsic::transmute()` function, which allows for converting between a type to another type whilst it is permitted in the type system.
With these changes, it is now possible to define a simple printing function in the standard library prelude!
> codegen: fix handling of string and slice types, implement `transmute()` intrinsic

- Cargo.lock
- compiler/hash-lower/src/lib.rs
- compiler/hash-semantics/Cargo.toml
- compiler/hash-semantics/src/lib.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-tir/src/environment/env.rs
- compiler/hash-typecheck/src/inference.rs
Using the added `adjust_{float,lit}` functions by @feds01, this PR uses them to adjust the size of literals during inference to their true inferred type.
> Adjust literals during inference to their true type

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-intrinsics/src/utils.rs
- compiler/hash-pipeline/src/args.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-semantics/src/environment/sem_env.rs
- compiler/hash-semantics/src/lib.rs
- compiler/hash-semantics/src/passes/discovery/defs.rs
- compiler/hash-semantics/src/passes/evaluation/mod.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-semantics/src/passes/resolution/defs.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
- compiler/hash-untyped-semantics/src/visitor.rs
This PR adds monomorphisation support to TC. Every `pure` function or an expression with `#run` will be evaluated at compile-time. In effect, generic calls are reduced to their monomorphised equivalents, appropriate for lowering.
This PR also:
- Adds the `#pure` directive for functions, to label them as pure without having to use the `<>` syntax.
- Adds the `#run` directive to run any expression at compile time
- Implements weak-head normalisation so that the unification can use it.
There are still a few things to do:
- Assign atom info to all monomorphised terms so that the lowering can actually process them
- Assign nice names to monomorphised functions
The monomorphisation can be turned off with `-Cmono=off` if needed (for debugging).
Closes #835
> Implement monomorphisation of terms

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-ir/src/write/pretty.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/matches/declarations.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-semantics/src/passes/discovery/defs.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-semantics/src/passes/resolution/paths.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-semantics/src/passes/resolution/scoping.rs
- compiler/hash-tir/src/ast_info.rs
- compiler/hash-tir/src/control.rs
- compiler/hash-tir/src/environment/context.rs
- compiler/hash-tir/src/pats.rs
- compiler/hash-tir/src/scopes.rs
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-tir/src/utils/context.rs
- compiler/hash-tir/src/utils/stack.rs
- compiler/hash-tir/src/utils/traversing.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
This PR fixes some issues with unification, and unifies `StackMemberId`/`ArgId` bindings into `Decl`. This makes a lot of things simpler, and now members can be looked up just by symbol.
Some groundwork has been added to make inference and unification modifying rather than copying, which should greatly improve performance but also retain locations automatically.
> Simplify context bindings

- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-ir/src/cast.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write/graphviz.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-ir/src/write/pretty.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-lower/src/lower_ty.rs
- compiler/hash-typecheck/src/normalisation.rs
- stdlib/prelude.hash
This patch fixes the following issues:
- lower: support recursive data types
- lower: don't emit an assignment for enum variants that have no associated data fields.
- codegen: properly generate code for setting enum discriminants
- codegen: disable `volatile` flag setting on `memmove`, `memcpy`, and `memset` since `inkwell`/`llvm-sys` don't support setting this flag.
> lower+codegen fixes

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast-expand/src/visitor.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/write/mod.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-layout/src/write.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/mod.rs
- compiler/hash-lower/src/optimise/simplify_graph.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/args.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/workspace.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-utils/src/tree_writing.rs
- tests/cases/lowering/return_if.hash
- tests/cases/lowering/return_if.stdout
This fixes some issues with displaying IR types and layouts. This also adds some additional configuration to the compilation in order to specify whether to emit `checked-operations` or which character set to use when printing compiler messages.
> various fixes 

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-intrinsics/src/primitives.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-semantics/src/diagnostics/error.rs
- compiler/hash-semantics/src/lib.rs
- compiler/hash-semantics/src/old/traverse/visitor.rs
- compiler/hash-semantics/src/passes/discovery/visitor.rs
- compiler/hash-semantics/src/passes/evaluation/mod.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-semantics/src/passes/resolution/defs.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-semantics/src/passes/resolution/scoping.rs
- compiler/hash-session/src/lib.rs
- compiler/hash-tir/src/tys.rs
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-tir/src/utils/context.rs
- compiler/hash-tir/src/utils/data.rs
- compiler/hash-tir/src/utils/params.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
- stdlib/eq.hash
- stdlib/prelude.hash
This PR:
- Modifies the way that inference and unification is done so that new terms don't have to be created all the time. This retains most locations automatically.
- Adds dependent pattern matching support (and equality identities in Prelude), as well as the ability to define inductive data types with indices to the parser.
- Fixes a lot of issues with the previous inference.
- The analysis only requires an entry point if the target stage is `> Lowering`.
Closes #841.
Unfortunately there are still a few places where locations aren't set due to copying, hopefully this can be done soon.
> Refactor inference, add dependent pattern matching and definitions, optional entry point

- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash/src/main.rs
- stdlib/prelude.hash
- stdlib/printing.hash
- stdlib: fix `print_int` not printing zeros
- codegen(llvm): fix panic with return value being a scalar pair
- core: make `exe` mode wait for the child process to exit
> compiler+codegen: fix several issues

- compiler/hash-typecheck/src/inference.rs
- stdlib/prelude.hash
When fn calls were inferred, the whole context was substituted rather than the local scope, which caused serious performance issues for blocks containing a lot of expressions. This has been remedied by entering a temporary substitution scope while inferring function calls, which keeps the context to be substituted very small. Performance of the 100K printing file has been restored to more-or-less the same as before.
However, there is still lots of room for improvement. It would be good to have a better in-place substitution mechanism that doesn't need to create an intermediary `Sub` and can just look at the context.
> tc: fix perf regression in inference due to context substitutions

- compiler/hash-codegen/src/lower/abi.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-lower/src/optimise/simplify_graph.rs
- compiler/hash-parser/src/parser/pat.rs
- compiler/hash-target/src/targets/windows_msvc_base.rs
- compiler/hash/src/logger.rs
- lower: fix bug where parent statement wasn't being removed after all uses were eliminated
- compiler: use `##` for notes instead of `@@`
> lower: fix bug in local elimination pass

- compiler/hash-semantics/src/passes/evaluation/mod.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
This is an unused flag that can be safely removed.
Closes #865
> Remove eval_impure_fns flag from normalisation mode

- .github/workflows/rust.yml
- compiler/hash-codegen/src/lower/abi.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-source/src/location.rs
- compiler/hash-utils/src/range_map.rs
- reporting: use new `LineRanges` for computing column and row offsets
- source: remove `compute_row_col_from_offset`
- chore: re-format some sources
> reporting: use `LineRanges` to compute columns and rows

- Cargo.lock
- compiler/hash-tir/Cargo.toml
- compiler/hash-tir/src/args.rs
- compiler/hash-tir/src/data.rs
- compiler/hash-tir/src/environment/env.rs
- compiler/hash-tir/src/environment/stores.rs
- compiler/hash-tir/src/fns.rs
- compiler/hash-tir/src/mods.rs
- compiler/hash-tir/src/params.rs
- compiler/hash-tir/src/pats.rs
- compiler/hash-tir/src/symbols.rs
- compiler/hash-tir/src/terms.rs
- compiler/hash-tir/src/tys.rs
This PR implements the first two task items of #816.
First, it adds a `STORES` thread local variable which provides static access to TIR stores without requiring `Env`. It also adds a few traits for `XId` types to implement, which allow dereferencing to the actual data, modifying the data, as well as creating data inside `STORES`.
Code should not be modified yet to use `STORES` or these new traits, because they are not currently utilised in the rest of the compiler.
> tc: Make TIR stores static and implement convenience methods for IDs

- compiler/hash-tir/src/data.rs
- compiler/hash-tir/src/defs.rs
- compiler/hash-tir/src/mods.rs
- compiler/hash-tir/src/params.rs
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/normalisation.rs
Done after the change `s/self.env().with//g`
> Remove unnecessary parentheses from formatting

- compiler/hash-intrinsics/src/intrinsics.rs
- compiler/hash-semantics/src/passes/resolution/exprs.rs
- compiler/hash-tir/src/environment/stores.rs
- compiler/hash-tir/src/scopes.rs
- compiler/hash-tir/src/terms.rs
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-utils/src/store.rs
This PR adds `borrow()` and `borrow_mut()` on types implementing `StoreId`. This is an alternative to using `map()`. For example, `term_id.map(|t| t.to_string())` can be turned into `term_id.borrow().to_string()`. Sometimes it is handy and more ergonomic to avoid closures.
This PR also adds `Term::void()` as a starting point for deprecating store methods that depend on `Env`.
> Add borrowing methods to `StoreId`

- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-exhaustiveness/src/range.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-target/src/primitives.rs
- compiler/hash-target/src/size.rs
- compiler/hash-tir/src/lits.rs
Change `IntTy::size()` `IntTy::min()` and `IntTy::max()` functions to
avoid returning an `Option<..>`. It is now assumed that querying this
information on `ubig` and `ibig` types is an invalid operation, and hence
will panic.
Additionally, added `numeric_min()` and `numeric_max()` to compute the
min and maximum values in the form of a `u128`. This is useful for exhaustiveness
and other parts of the compiler where the min/max is needed in an encoded
form.
> target: avoid awkward API for querying sizes/max/mins when handling bigints

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-exhaustiveness/src/lower.rs
- compiler/hash-exhaustiveness/src/range.rs
- compiler/hash-fmt/src/lib.rs
- compiler/hash-intrinsics/src/utils.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/const_range.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-parser/src/parser/lit.rs
- compiler/hash-parser/src/parser/pat.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-tir/src/pats.rs
- compiler/hash-tir/src/utils/mod.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-untyped-semantics/src/diagnostics/error.rs
- compiler/hash-untyped-semantics/src/visitor.rs
- tests/cases/exhaustiveness/open_ranges.hash
- tests/cases/exhaustiveness/open_ranges.stderr
- tests/cases/parser/patterns/incomplere_exclusive_range_pat.hash
- tests/cases/parser/patterns/incomplere_exclusive_range_pat.stderr
- tests/cases/parser/patterns/incomplete_range_pat.hash
- tests/cases/parser/patterns/incomplete_range_pat.stderr
- tests/cases/semantics/incomplete_range_ending.hash
- tests/cases/semantics/incomplete_range_ending.stderr
- target: avoid awkward API for querying sizes/max/mins when handling bigints
- parser+ast: support open ranges, i.e. omit start and or end
- tir: specify `RangePat` `lo` and `hi` values as optionals
- exhaustiveness: support open pattern ranges
- tc: support open ranges in patterns
- lower: support open ranges in lowering
- tests: add tests for open ranges in patterns and remove outdated tests
> support open ranges in patterns, i.e. `4..`, `..<5` `..`, etc

- compiler/hash-tir/src/context.rs
This reduces the size of `Scope` from 104bytes to 88bytes
> tir: use FxBuildHasher for scope hashing

- Cargo.lock
- compiler/hash-ast/Cargo.toml
- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-tir/Cargo.toml
- compiler/hash-tir/src/ast_info.rs
- compiler/hash-tir/src/locations.rs
- compiler/hash-tir/src/problems.rs
- compiler/hash-tir/src/scopes.rs
- compiler/hash-tree-def/src/emit.rs
- compiler/hash-utils/src/lib.rs
- ast: Make AST spanless, and store `Span`s within `SPAN_MAP`
- ast: Use `RwLock` and `once_cell:sync::Lazy` for SpanMap
> spanless ast

- compiler/hash-ir/src/ty.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/discover.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/lower_ty.rs
- compiler/hash-utils/src/lib.rs
- lower: avoid `.value()` on `FnDef`
- lower: optimise type lowering to avoid needlessly creating `()` which removes creating a lot of unneeded ADTs for just units. In some extreme cases, this led to a speedup of 20-25% and significantly less memory usage (in order of magnitude of MB).
> Speedup lowering by 20-25%

- Cargo.lock
- compiler/hash-exhaustiveness/Cargo.toml
- compiler/hash-exhaustiveness/src/diagnostics.rs
- compiler/hash-reporting/src/diagnostic.rs
- compiler/hash-reporting/src/lib.rs
- compiler/hash-semantics/Cargo.toml
- compiler/hash-semantics/src/diagnostics/error.rs
- compiler/hash-tir/Cargo.toml
- compiler/hash-tir/src/utils/common.rs
- compiler/hash-tir/src/utils/mod.rs
- compiler/hash-tir/src/utils/params.rs
- compiler/hash-typecheck/Cargo.toml
- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/unification.rs
- compiler/hash-untyped-semantics/Cargo.toml
- compiler/hash-untyped-semantics/src/diagnostics/error.rs
- reporting: re-export `hash-error-codes` and update references across compiler
- tc+tir: factor out parameter/argument validation into `hash-tir` from `hash-typecheck`
closes #922 
- Possibly refactor `TcErrorState` to just use the `hash_reporting::diagnostics::ErrorState`
> TC: factor out parameter/argument validation into `hash-tir`

- compiler/hash-lower/src/discover.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-tir/src/lib.rs
- compiler/hash-tir/src/visitor.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
Instead of having `fmap_*` and `visit_*` functions for each TIR node, this PR replaces those with implementations of `Visit<*>` and `Map<*>`, so that functions can be implemented for any `T` that has `Map<T>` or `Visit<T>`. This reduces a lot of duplication in TC substitutions, and allows specialised functions to be created generically, for example to copy nodes, or to visit infallibly.
> TIR: Add `Map` and `Visit` traits to the `tir::Visitor` in order to reduce code duplication

- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-driver/src/lib.rs
- compiler/hash-exhaustiveness/src/construct.rs
- compiler/hash-exhaustiveness/src/deconstruct.rs
- compiler/hash-exhaustiveness/src/fields.rs
- compiler/hash-exhaustiveness/src/lib.rs
- compiler/hash-exhaustiveness/src/lower.rs
- compiler/hash-exhaustiveness/src/matrix.rs
- compiler/hash-exhaustiveness/src/range.rs
- compiler/hash-exhaustiveness/src/stack.rs
- compiler/hash-exhaustiveness/src/storage.rs
- compiler/hash-exhaustiveness/src/usefulness.rs
- compiler/hash-exhaustiveness/src/wildcard.rs
- compiler/hash-link/src/lib.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/interface.rs
- compiler/hash-semantics/src/env.rs
- compiler/hash-semantics/src/lib.rs
- compiler/hash-semantics/src/passes/tc_env_impl.rs
- compiler/hash-tir/src/context.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-utils/src/timing.rs
This PR brings speedups of exhaustiveness from 3x-5x by the following changes:
This PR switches the internal exhaustiveness stores to just use `Vec`s over the `Store` interface. This avoids the locking mechanism for stores which never need to be locked. 
Additionally, this also switches `Fields` to use a `ThinVec` over a `Vec` which leads to better performance and less memory use overall.
Finally, we don't need to store the `bias` on an `IntRange` directly, only when we need to convert back into normal values, so remove it from the `IntRange` struct.
In addition to performance improvements, the analysis phase now records the time taken for exhaustiveness to complete its operations, and reports them through the standard compiler metrics plumbing.
> exhaustiveness: speedup checking 3x-5x

- compiler/hash-lexer/src/lib.rs
This bug was being triggered in the interactive session where content usually doesn't have a `\r\n` or `\n` endings, and thus the lexer wouldn't go out of bounds when trying to lex numeric literal tokens.
> fix improper handling of EOFs in lexer

- Cargo.lock
- compiler/hash-driver/src/driver.rs
- compiler/hash-lexer/src/error.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-parser/src/parser/name.rs
- compiler/hash-pipeline/src/workspace.rs
- compiler/hash-reporting/Cargo.toml
- compiler/hash-reporting/src/lib.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-reporting/src/report.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-source/src/location.rs
- tests/cases/parser/literals/byte_literals/combining_marks.hash
- tests/cases/parser/literals/byte_literals/combining_marks.stderr
- tests/cases/parser/literals/byte_literals/non_ascii_byte_literals.hash
- tests/cases/parser/literals/byte_literals/non_ascii_byte_literals.stderr
- tests/cases/parser/literals/characters/combining_marks.hash
- tests/cases/parser/literals/characters/combining_marks.stderr
- tests/cases/parser/literals/characters/multi_error_char.stderr
- tests/cases/reporting/pre_code_marks.hash
- tests/cases/reporting/pre_code_marks.stderr
This PR deals with several issues arising from Unicode handling in the compiler. Firstly, the compiler would completely bork when it encountered combining marks. Column offsets and reporting rendering were completely incorrect, and the lexer error message was somewhat confusing. So, this PR does the following:
- lexer: emit error for non-ASCII byte literals
- source: correctly compute column offsets (accounting for Unicode)
- reporting: account for combining marks when drawing span annotations
- lexer: improve errors for combining marks in byte and character literals
- fix #1003
> lexer: better handling of character and byte literals

- INSTALL.md
The previous LLVM installation instructions did not work (at least on macOS due to a homebrew issue relating to GitHub authorisation during installation). It is easier to request people to install the specific LLVM version from the releases page, and set the appropriate environment variables for `inkwell` to find it.
> Update LLVM installation instructions

- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/mod.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-ir-utils/src/graphviz.rs
- compiler/hash-ir-utils/src/lib.rs
- compiler/hash-ir-utils/src/pretty.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-ir/src/visitor.rs
- compiler/hash-lower/src/build/into.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/build/matches/declarations.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/mod.rs
- compiler/hash-lower/src/build/place.rs
- compiler/hash-lower/src/build/rvalue.rs
- compiler/hash-lower/src/build/temp.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-storage/src/store/sequence/local.rs
- compiler/hash-storage/src/store/sequence/mod.rs
- compiler/hash-storage/src/store/sequence/shared.rs
- compiler/hash-tir/src/stores.rs
- compiler/hash-tir/src/tir/args.rs
This PR makes all of the projections that are applied to a body local to the `Body` rather than being externally stored in a static store. The implementation isn't as clean as I'd hoped it to be (especially in the visitor parts).
- ir: localise `Projections` to each `Body`
- ir: cleanup `IrVisitorMut` with `VisitorCtx`
- ir: cleanup `ModiyfyingIrVisitor` with `IrVisitorCtxMut`
closes #996
> ir: Make projections local to a `Body`

- Cargo.lock
This should also patch the security alert through `dependabot`
> chore: upgrade dependencies

- compiler/hash-utils/src/context.rs
- compiler/hash-utils/src/lib.rs
- compiler/hash-utils/src/scoping/mod.rs
This PR adds a generic context structure that can be used by multiple stages of the compiler. It will replace the current TIR-specific context, and also be used for name checking which is a stage that will be added soon (#1017). Additionally, it can be used from within lowering in the future.
The new context uses two-level de-Brujin levels, where each member is indexed by an integer pair `(s, m)`, `s` indexing into the stack of scopes in the `context`, and `m` indexing into the scope `context[m]`. 
Once replaced in the TIR, this should dramatically speed up context accesses, which are currently performed through hashmaps on the scope level and linear search on the whole context level.
Closes #1020
> utils: Add a context module that uses de-Brujin levels for constant-time indexing

- compiler/hash-source/src/location.rs
Spotted this bug in the wild whilst demoing 😬
> reporting: fix out of bounds bug for reporting lines at the end of source

- compiler/hash-attrs/src/builtin.rs
- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-driver/src/lib.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-target/src/lib.rs
- compiler/hash-tir/src/intrinsics/make.rs
- chore: fix clippy and macro-metavar compilation issues
- target: store `TargetDataLayout` on `Target`
> Store `TargetDataLayout` on `Target`

- compiler/hash-codegen-llvm/src/translation/abi.rs
- compiler/hash-link/src/linker/mod.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-lower/src/optimise/mod.rs
- compiler/hash-lower/src/optimise/simplify_graph.rs
This PR adds metrics to the optimisation passes that occur during lowering. This has two effects:
- we can no more accurately monitor and keep track of certain performance bottlenecks during IR optimisation.
- stop clippy from complaining about `IrOptimisationPass:name()` not being used.
Also:
- allow dead code in linker implementation (that will be used in the future for libraries)
- remove some dead code in `hash-codegen` and respective backends
> lower: add metrics to optimisation passes

- Cargo.lock
- compiler/hash-codegen-llvm/src/translation/builder.rs
Relevant inkwell upstream changes: https://github.com/hash-org/inkwell/commit/b28e8528aeb803c2ab779964486eabfc37ab731d#diff-05702e78430359853e5b38404035fa394540368bee185a2cdc936a62b9cd65b0
This applies the fixes and changes that are needed after inkwell is updated to version `0.4.0`.
Also:
This updates all dependences
> codegen(llvm): update inkwell and dependencies

- Cargo.lock
- compiler/hash-backend/Cargo.toml
- compiler/hash-backend/src/lib.rs
- compiler/hash-codegen-bytecode/src/lib.rs
- compiler/hash-codegen-vm/Cargo.toml
- compiler/hash-codegen-vm/src/lib.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-driver/Cargo.toml
- compiler/hash-messaging/Cargo.toml
- compiler/hash-messaging/src/lib.rs
- compiler/hash-pipeline/Cargo.toml
- compiler/hash-pipeline/build.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash/Cargo.toml
- **messaging: add `hash_messaging` crate**
- **fix fmt issue**
- **pipeline: add more verbose version of the compiler**
- **compiler: make compiling LLVM backend optional**
- **codegen(vm): rename crate to `vm` from `bytecode` and add basic impl**
Relates to https://github.com/hash-org/hashc/issues/976
> Allow for disabling compilation of LLVM backend

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-expand/src/lib.rs
- compiler/hash-ast-utils/src/tree.rs
- compiler/hash-ast/src/node_map.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/workspace.rs
- compiler/hash-semantics/src/passes/discovery/mod.rs
- compiler/hash-semantics/src/passes/discovery/visitor.rs
- compiler/hash-semantics/src/passes/mod.rs
- compiler/hash-untyped-semantics/src/lib.rs
This fixes issue #980 and other similar issues where given that multiple imports are being simultaneously parsed, the insertion order of the modules in `NodeMap` is not correctly preserved when using a `Vec`. This comes from the fact that the parser generates the corresponding `ModuleId`. To respect the order of insertion, we use a map between the generated `ModuleId` and the parsed `Module`s.
fixes #980
fixes #982
> Fix import resolution logic

- compiler/hash-ast/src/lib.rs
- compiler/hash-attrs/src/lib.rs
- compiler/hash-codegen/src/lib.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/mod.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/symbols/mangle.rs
- compiler/hash-link/src/linker/gcc.rs
- compiler/hash-lower/src/build/matches/candidate.rs
- compiler/hash-lower/src/optimise/cleanup_locals.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-repr/src/compute.rs
- compiler/hash-repr/src/write.rs
- compiler/hash-semantics/src/passes/discovery/discriminants.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-utils/src/scoping/mod.rs
This PR does the following:
- Clippy now checks that paragraphs and lists are properly aligned in comments, this PR fixes the newly detected issues.
- Furthermore, `lazy_cell` feature was stabilised, therefore the feature flag is no longer needed.
> chore: fix clippy

- Cargo.lock
- compiler/hash-ast-expand/src/attr.rs
- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-driver/src/driver.rs
- compiler/hash-driver/src/lib.rs
- compiler/hash-error-codes/src/lib.rs
- compiler/hash-lower/src/ctx.rs
- compiler/hash-lower/src/lib.rs
- compiler/hash-messaging/src/lib.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/metrics.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/workspace.rs
- compiler/hash-reporting/src/report.rs
- compiler/hash-source/src/lib.rs
- compiler/hash-source/src/location.rs
- compiler/hash-tir/src/context.rs
- compiler/hash-tir/src/dump.rs
- compiler/hash-utils/Cargo.toml
- compiler/hash-utils/src/logging.rs
- compiler/hash-utils/src/profiling.rs
- compiler/hash/src/main.rs
- tests/runner.rs
- **pipeline: move `metrics` implementation out of `hash-driver`**
- **logging: add JSON output format**
- **driver: use new `Metrics` type for profiling**
- **messaging: use `CompilerOutputMessage` for `log::info!`s**
- **driver: add configuration for messaging format**
> json messaging format

- compiler/hash-pipeline/src/settings.rs
- compiler/hash-utils/src/logging.rs
- **meta: ensure `zstd` is added to link path**
- **settings: ensure `messaging_format` is propagated from `--configure`**
- **driver: disallow `--configure` unknown fields**
- **settings: default serde serialization/deserialization to use kebab-case for enums**
> Various metrics comms fixes

- .cargo/config.toml
- Cargo.lock
- compiler/hash-storage/src/store/sequence/shared.rs
- compiler/hash-typecheck/src/env.rs
## Description
This PR upgrades all dependencies to their latest versions. This PR also
upgrades the Rust toolchain to the latest version, and fixes any issues
that came along with the upgrade.
- **chore: run fmt**
- **chore: fix `rustc` warning about elided lifetimes**
- **chore: globally disable `clippy::too_long_first_doc_paragraph` lint**
- **chore: upgrade all deps**
> chore: updates to toolchain and dependencies

- compiler/hash-ast/src/ast.rs
- compiler/hash-codegen-llvm/src/misc.rs
- compiler/hash-codegen-llvm/src/translation/mod.rs
- compiler/hash-repr/src/ty.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-tir/src/building.rs
## Description
This PR fixes newly detected issues by `clippy` and `rustfmt`.
> chore: fixes from formatting and clippy upgrade

- compiler/hash-ir-utils/src/graphviz.rs
- compiler/hash-lower/src/optimise/mod.rs
- compiler/hash-pipeline/src/settings.rs
- tests/cases/lowering/early_returns.stdout
- tests/cases/lowering/nested_loops.stdout
This PR fixes a few issues with the lowering settings being propagated and with the graphviz
output format which unexpectedly changed the block ids.
Finally, the `SimplifyGraphPass` is now run before and after the `CleanupLocalPass` to ensure that now-empty blocks are also removed
after the lowering.
- **pipeline: run post-init hooks after settings initialisation**
- **pipeline: `LoweringSettings` merge should inherit rhs values**
- **lower: fix graphviz block ids**
- **lower: run `SimplifyGraphPass` pre & post `CleanupLocalPass`**
> lower: fix Graphviz output and settings

- compiler/hash-parser/src/parser/expr.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-parser/src/parser/ty.rs
- compiler/hash-reporting/src/macros.rs
- compiler/hash-source/src/location.rs
- compiler/hash-token/src/cursor.rs
- compiler/hash-token/src/lib.rs
- tests/cases/parser/blocks/empty_for_loop.hash
- tests/cases/parser/constructors/struct_defn.hash
- tests/cases/parser/misc/while_implicit_call.hash
- tests/cases/parser/patterns/list_patterns.hash
- tests/cases/typecheck/pat_binds/548.hash
- tests/cases/typecheck/pat_binds/548.stderr
This PR changes a few things:
- The parser's handling of singular expressions, now we consider single expressions as those that must be physically connected.
- Avoid emitting redundant parenthesis warnings on deref expressions, as
parentheses are required to disambiguate what expression is being dereferenced.
- Fix a panic that would occur when trying to parse malformed implicit arguments.
To elaborate on single expression handling,
i.e. ones that don't have any operators between them. Previously, the
parser would eagerly continue parsing a singular expression until it
matched the legal structure of an expression. Whilst this was legal,
and handled accordingly at later phases of compilation, it certainly
created odd (and unexpected) behaviour in the parser.
Now, we consider singular …
> Fix several parser bugs

- compiler/hash-ast/src/ast.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-parser/src/parser/ty.rs
- tests/cases/parser/types/tuple_type_args.hash
## Description
This PR removes the `source_id` field from the `LocalSpanMap` struct. This field was used to store the `source_id` of the span that was being parsed, but it was not being used anywhere. This PR also ensures that we abort parsing type arguments when there is an actual error.
## Commits
- **Remove `source_id` from `LocalSpanMap`**
- **Ensure we abort parsing type arguments when there is an actual error**
> Refactor and simplify syncingspan maps

- .github/workflows/rust.yml
- Cargo.lock
- compiler/hash-ast-utils/src/pretty/mod.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-codegen-llvm/src/translation/layouts.rs
- compiler/hash-exhaustiveness/src/fields.rs
- compiler/hash-ir/src/ir.rs
- compiler/hash-ir/src/lib.rs
- compiler/hash-link/src/platform/apple.rs
- compiler/hash-lower/src/build/block.rs
- compiler/hash-reporting/src/render.rs
- compiler/hash-repr/src/write.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-target/src/size.rs
- compiler/hash-tree-def/src/definitions.rs
- compiler/hash-tree-def/src/parse.rs
- compiler/hash-utils/src/profiling.rs
- compiler/hash-utils/src/tree_writing.rs
- compiler/hash-vm/src/heap.rs
- **Use `iter::repeat_n` instead of `iter::repeat`**
- **Update attributes syntax, and drop auto-enabled features**
- **Use `!items.is_empty()` instead of `items.len() > 0`**
- **Drop redundant `{ .. }` for unit patterns**
- **Use `io::error::other` constructor rather than variant directly**
- **Use `Option::replace` instead of `mem::replace`**
- **Box `ty` in `NodeFieldData` variant to shrink variant size**
- **Use `div_ceil` directly to illustrate overflow handling in size calcs**
- **Upgrade compiler dependencies**
> Upgrade dependencies and Rust versions

- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-ir/src/cast.rs
- stdlib/prelude.hash
Add `input` function implementation to the prelude.
In order for this implementation to work, we needed to implement the
ability for the compiler to support `ref` to `int` and `int` to `ref` casts.
> Implement `input` prelude function

- compiler/hash-parser/src/parser/expr.rs
- tests/cases/parser/attributes/parenthesised_attribute_calls.hash
- tests/cases/parser/attributes/parenthesised_attribute_calls.stderr
- tests/runner.rs
We prevent the parser from emitting useless parenthesis warnings for macro invocations:
```
warn: unnecessary parentheses around expression
--> tests/cases/parser/attributes/parenthesised_attribute_calls.hash:8:25
7 |       // function.
8 |       buf := libc::malloc((#size_of T) * size);
|                           ^^^^^^^^^^^^ 
9 |       transmute<_, [T]>(buf)
```
After this PR, we no longer emit these.
> parser: fix erroneus emission of " useless paren" warning for  directive invocations
