hash-org/hashc

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- examples/lang_manifest.hash
- src/main.rs
- src/pest_parser/hash.pest
- src/pest_parser/mod.rs
- Implemented the language grammar using pest.
Still to do:
> Language Grammar

- hash-parser/src/ast.rs
- hash-parser/src/emit.rs
- hash-parser/src/grammar.rs
- hash-parser/src/hash.pest
- hash-parser/src/lib.rs
Also add some scaffolding for AST translation.
> Modify grammar to make it easier to parse into AST

- README.md
We don't want to fend off any newcomers :)
> Add link to the Hash book in the lang README

- compiler/hash-ast/src/operator.rs
- compiler/hash-parser/src/operator.rs
> fix: use `Debug` formatter for converting the `OperatorKind` instead of `Display`

- Cargo.lock
- Cargo.toml
- compiler/hash-ast/src/tree.rs
- compiler/hash-interactive/Cargo.toml
- compiler/hash-interactive/src/lib.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/scope.rs
- compiler/hash-typecheck/src/traverse.rs
- compiler/hash-typecheck/src/types.rs
- compiler/hash-typecheck/src/unify.rs
- compiler/hash-typecheck/src/writer.rs
This PR implements a minimum viable version of enums in the current typechecker.
> Typecheck: Implement enums

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/count.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/gen.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/refutability.rs
- compiler/hash-typecheck/src/traverse.rs
> typechecker: implement refutability check.

- compiler/hash-ast/src/operator.rs
- compiler/hash-parser/src/gen.rs
This fixes a minor issue with the AST transformation when parsing `while` loops.
> Fix while transformation

- compiler/hash-typecheck/src/traverse.rs
> reporting: fix issue where access name locations were inaccurate

- docs/src/SUMMARY.md
- docs/src/features/functions.md
- docs/src/features/intro.md
- docs/src/features/name-bindings.md
This includes formal grammar for function definitions and function calls.
Closes #191.
> Add documentation section about functions

- docs/src/features/functions.md
- docs/src/features/type-functions.md
This includes a formal grammar for type function definitions and calls. Closes #190.
> Add documentation section about type functions

- docs/src/features/structs-enums.md
> Add documentation section on structs and enums

- docs/src/SUMMARY.md
- docs/src/features/modules.md
Closes #195. Includes formal grammars.
> Write documentation section about modules and visibility

- docs/src/SUMMARY.md
- docs/src/features/patterns.md
Closes #199. Includes formal grammar.
> Docs: Update documentation on patterns

- docs/src/features/types.md
This was missed in the previous PR.
> Add a function type to the grammar of types

- compiler/hash-parser/src/parser/error.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/literal.rs
- compiler/hash-parser/src/parser/mod.rs
- compiler/hash-parser/src/parser/operator.rs
- compiler/hash-parser/src/parser/pattern.rs
- compiler/hash-token/src/lib.rs
- tests/parser/tests/cases/should_fail/dangling_parenthesis/case.stderr
- tests/parser/tests/cases/should_fail/incomplete_spread_pattern/case.stderr
- tests/parser/tests/cases/should_fail/issue_223/case.hash
- tests/parser/tests/cases/should_fail/issue_223/case.stderr
- tests/parser/tests/cases/should_fail/malformed_access_name/case.stderr
- tests/parser/tests/cases/should_fail/pat_match_missing_semi/case.stderr
- tests/parser/tests/cases/should_fail/spread_pattern_in_namespace_pattern/case.stderr
- tests/parser/tests/cases/should_fail/spread_pattern_in_struct_pattern/case.stderr
- tests/parser/tests/test_runner.rs
This patch improves some aspects of error reporting within the parser.
Also:
fixes #224 
fixes #223
> Parser: various fixes

- Cargo.lock
- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-passes/Cargo.toml
- compiler/hash-ast-passes/src/error.rs
- compiler/hash-ast-passes/src/lib.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/settings.rs
- compiler/hash-pipeline/src/traits.rs
- compiler/hash/src/main.rs
> Semantics: implement `continue` and `break` outside of loop checking

- compiler/hash-ast-passes/src/analysis/block.rs
- compiler/hash-ast-passes/src/analysis/error.rs
- compiler/hash-ast-passes/src/analysis/mod.rs
- compiler/hash-ast-passes/src/visitor.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-parser/src/parser/pattern.rs
> semantics: implement semantic checking of mutability and visibility modifiers

- compiler/hash-ast-desugaring/src/lib.rs
- compiler/hash-ast-passes/src/lib.rs
- compiler/hash-ast/src/ast.rs
- compiler/hash-interactive/src/lib.rs
- compiler/hash-parser/src/lib.rs
- compiler/hash-pipeline/src/lib.rs
- compiler/hash-pipeline/src/sources.rs
- compiler/hash-typecheck/src/error.rs
- compiler/hash-typecheck/src/fmt.rs
- compiler/hash-typecheck/src/lib.rs
- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/reader.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/reporting.rs
- compiler/hash-typecheck/src/storage/scope.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This includes:
- Body blocks
- Literal expressions (most of them)
- Function definitions
- Names and access names
After this PR we should add a few more code comments on the traversal stuff to clarify all the steps (especially for function definitions).
> TC: Implement some traversal basics

- compiler/hash-ast/src/ast.rs
- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-parser/src/parser/definitions.rs
- compiler/hash-parser/src/parser/types.rs
- compiler/hash-typecheck/src/traverse/mod.rs
> ast: Support `default` arguments on `TypeFunctionDefParam`

- compiler/hash-typecheck/src/traverse/mod.rs
This pr partially implements #340 and another following PR will add traversal for traits and trait implementations.
> tc: implement `mod` block traversals

- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/storage/core.rs
- compiler/hash-typecheck/src/storage/scope.rs
- compiler/hash-typecheck/src/traverse/mod.rs
This PR brings us another step closer to finishing implementing `mod`/`trait def`/`trait impl`s as per #340
> tc: implement trait definition traversal

- compiler/hash-parser/src/parser/expression.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- stdlib/prelude.hash
> tc: Implement traversal of `binary` and `unary` expressions

- compiler/hash-typecheck/src/ops/typing.rs
Closes #399. One step closer to implementing #331 and #329.
> TC: Implement getting the type and the term of a pattern

- compiler/hash-ast/src/tree.rs
- compiler/hash-ast/src/visitor.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-utils/src/path.rs
This patch implements traversals for cast expressions.
> tc: traverse cast expressions

- compiler/hash-typecheck/src/ops/discover.rs
- compiler/hash-typecheck/src/ops/params.rs
- compiler/hash-typecheck/src/ops/scope.rs
- compiler/hash-typecheck/src/ops/simplify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- compiler/hash-typecheck/src/traverse/scopes.rs
Fix a series of bugs relating to the new introductions of `SetBound` in #432. Also simplifies a lot of the scope entering/exiting code by using the `enter_scope` helper.
> TC: Bug fixing

- compiler/hash-typecheck/src/ops/building.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/ops/unify.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-utils/src/store.rs
Closes #455.
Also fixes a bug with sequence stores.
> BugFix: Fix problem where types are not runtime instantiable

- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- tests/cases/typecheck/functions/calling.hash
- tests/cases/typecheck/functions/inference.hash
- tests/cases/typecheck/functions/non-rt-arg.hash
- tests/cases/typecheck/functions/non-rt-arg.stderr
- tests/cases/typecheck/functions/non-rt-return.hash
- tests/cases/typecheck/functions/non-rt-return.stderr
- tests/cases/typecheck/functions/recursion.hash
- Fixed a bug where return type hint wasn't properly saved 
- Fixed a bug where function literals were not getting validated
> Add typechecking function tests and fix bugs

- compiler/hash-ast/src/tree.rs
- compiler/hash-typecheck/src/diagnostics/error.rs
- compiler/hash-typecheck/src/ops/oracle.rs
- compiler/hash-typecheck/src/ops/validate.rs
- compiler/hash-typecheck/src/traverse/mod.rs
- tests/cases/typecheck/traits/comppund_errors.hash
- tests/cases/typecheck/traits/comppund_errors.stderr
> TC: Polish trait validation checking and error reporting

- compiler/hash-semantics/src/new/passes/inference/mod.rs
- compiler/hash-tir/src/new/utils/traversing.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/substitution.rs
This PR adds a loop to the inference semantic stage to infer terms until there are no more holes. Additionally, data definitions are now traversed and inferred.
Closes #734, closes #745 
Next up: #739
> Add inference loop and infer data types

- compiler/hash-typecheck/src/errors.rs
- compiler/hash-typecheck/src/inference.rs
Apparently I didn't commit some changes..
> Follow-up fix on previous PR

- compiler/hash-semantics/src/passes/resolution/exprs.rs
This does not yet properly deal with the case where the LHS has side effects, such as `land_on_moon()[0] += 1`. It will land on the moon twice. Dealing with this requires more complex de-sugaring and assigning to a temporary first.
> Implement resolution of assign-op

- compiler/hash-lower/src/build/mod.rs
- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-semantics/src/passes/resolution/paths.rs
- compiler/hash-semantics/src/passes/resolution/pats.rs
- compiler/hash-semantics/src/passes/resolution/scoping.rs
- compiler/hash-tir/src/environment/context.rs
- compiler/hash-tir/src/utils/context.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
- stdlib/prelude.hash
This PR fixes the issue where match bindings do not get added to the match case context. It also simplifies how context is kept track of.
> Fix some issues with match bindings

- compiler/hash-semantics/src/passes/inference/mod.rs
- compiler/hash-tir/src/utils/context.rs
- compiler/hash-tir/src/utils/traversing.rs
- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/normalisation.rs
- compiler/hash-typecheck/src/substitution.rs
- compiler/hash-typecheck/src/unification.rs
Mismatching array lengths no longer panic
> Fix some panics during inference

- compiler/hash-lower/src/build/ty.rs
- compiler/hash-source/src/constant.rs
- compiler/hash-typecheck/src/inference.rs
This PR fixes an issue where generic constructors were not properly typed in pattern position.
> Fix inference of constructor patterns

- compiler/hash-typecheck/src/inference.rs
- compiler/hash-typecheck/src/unification.rs
This PR adds support for inference of `return` statements inside function defs, which were previously not handled.
Closes #828
> Add proper inference support for return terms

- compiler/hash-typecheck/src/inference.rs
> Remove old println line in inference

- compiler/hash-abi/src/lib.rs
- compiler/hash-codegen-llvm/src/ctx.rs
- compiler/hash-codegen-llvm/src/translation/abi.rs
- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/intrinsics.rs
- compiler/hash-codegen-llvm/src/translation/layouts.rs
- compiler/hash-codegen-llvm/src/translation/mod.rs
- compiler/hash-codegen-llvm/src/translation/ty.rs
- compiler/hash-codegen/src/lower/abi.rs
- compiler/hash-codegen/src/lower/intrinsics.rs
- compiler/hash-codegen/src/lower/locals.rs
- compiler/hash-codegen/src/lower/mod.rs
- compiler/hash-codegen/src/lower/operands.rs
- compiler/hash-codegen/src/lower/place.rs
- compiler/hash-codegen/src/lower/rvalue.rs
- compiler/hash-codegen/src/lower/statement.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-codegen/src/lower/utils.rs
- compiler/hash-codegen/src/traits/builder.rs
- compiler/hash-codegen/src/traits/layout.rs
- compiler/hash-codegen/src/traits/mod.rs
- compiler/hash-layout/src/compute.rs
- compiler/hash-layout/src/lib.rs
- compiler/hash-layout/src/write.rs
- compiler/hash-lower/src/ctx.rs
And some code cleanup with it.
> Make layouts static

- compiler/hash-parser/src/parser/mod.rs
- chore: upgrade `smallvec` to `1.11.0`
- chore: fix clippy errors
- parser: always compute `parent_span` for `AstGen`
> parser: always compute `parent_span` for `AstGen`

- compiler/hash-codegen-llvm/src/translation/builder.rs
- compiler/hash-codegen-llvm/src/translation/intrinsics.rs
- compiler/hash-codegen/src/lower/intrinsics.rs
- compiler/hash-codegen/src/lower/terminator.rs
- compiler/hash-ir/src/intrinsics.rs
- compiler/hash-ir/src/lang_items.rs
- compiler/hash-ir/src/ty.rs
- compiler/hash-lower/src/build/matches/test.rs
- compiler/hash-lower/src/build/ty.rs
- compiler/hash-lower/src/build/utils.rs
- compiler/hash-source/src/identifier.rs
- compiler/hash-tir/src/intrinsics/definitions.rs
- stdlib/prelude.hash
> codegen: implement string comparisons - Part 2 

- Cargo.lock
- compiler/hash-codegen-llvm/Cargo.toml
Use organisation controlled inkwell repository
> update inkwell repository link

- Cargo.lock
- compiler/hash-ast-utils/src/attr.rs
- compiler/hash-repr/src/write.rs
- **chore: fix clippy issues**
- **chore: upgrade deps**
> Fix clippy and upgrade dependencies

- Cargo.lock
- compiler/hash-lexer/src/error.rs
- compiler/hash-lexer/src/lib.rs
- compiler/hash-source/Cargo.toml
- compiler/hash-source/src/location.rs
Fixes tests on Windows -  we now pass on Linux/MacOS/Windows!
> Fixes issues with line range reporting on Windows

- compiler/hash-pipeline/src/settings.rs
- compiler/hash/src/main.rs
> Fix opt level config

- Cargo.lock
- compiler/hash-utils/src/crash.rs
- **chore: fix clippy**
- **chore: upgrade deps**
> Upgrade dependencies and fix clippy

- compiler/hash-codegen-llvm/src/lib.rs
- compiler/hash-codegen-llvm/src/translation/constants.rs
- rust-toolchain.toml
- **Pin Rust toolchain via `rust-toolchain.toml`**
- **Remove uses of `HashMap::raw_entry_mut`**
> Pin Rust version via `rust-toolchain.toml`
